<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:response="urn:oio:sd:snitflader:2011.12.01" xmlns:tns="www.sd.dk/sdws/GetEmploymentChangedAtDate20111201" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:request="urn:oio:sd:snitflader:2011.12.01" name="GetEmploymentChangedAtDate20111201" targetNamespace="www.sd.dk/sdws/GetEmploymentChangedAtDate20111201" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema>
      <xsd:import schemaLocation="./xsd/SD_GetEmploymentChangedAtDateRequestInterface_20111201.xsd" namespace="urn:oio:sd:snitflader:2011.12.01" />
    </xsd:schema>
    <xsd:schema>
      <xsd:import schemaLocation="./xsd/SD_GetEmploymentChangedAtDateInterface_20111201.xsd" namespace="urn:oio:sd:snitflader:2011.12.01" />
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="GetEmploymentChangedAtDate20111201Response">
    <wsdl:part name="GetEmploymentChangedAtDate20111201" element="request:GetEmploymentChangedAtDate20111201" />
  </wsdl:message>
  <wsdl:message name="GetEmploymentChangedAtDate20111201Request">
    <wsdl:part name="GetEmploymentChangedAtDate" element="request:GetEmploymentChangedAtDate" />
  </wsdl:message>
  <wsdl:portType name="GetEmploymentChangedAtDate20111201PortType">
    <wsdl:operation name="GetEmploymentChangedAtDate20111201Operation">
      <wsdl:input message="tns:GetEmploymentChangedAtDate20111201Request" />
      <wsdl:output message="tns:GetEmploymentChangedAtDate20111201Response" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="GetEmploymentChangedAtDate20111201Binding" type="tns:GetEmploymentChangedAtDate20111201PortType">
    <wsdlsoap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="GetEmploymentChangedAtDate20111201Operation">
      <wsdlsoap:operation soapAction="https://service.sd.dk/sdws/services/GetEmploymentChangedAtDate20111201" />
      <wsdl:input>
        <wsdlsoap:body use="literal" namespace="urn:GetEmploymentChangedAtDate20111201" />
      </wsdl:input>
      <wsdl:output>
        <wsdlsoap:body use="literal" namespace="urn:GetEmploymentChangedAtDate20111201" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="GetEmploymentChangedAtDate20111201Service">
    <wsdl:port name="GetEmploymentChangedAtDate20111201" binding="tns:GetEmploymentChangedAtDate20111201Binding">
      <wsdlsoap:address location="https://service.sd.dk/sdws/services/GetEmploymentChangedAtDate20111201" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>