//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetOrganization
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.sd.dk/sdws/GetOrganization20111201", ConfigurationName="GetOrganization.GetOrganization20111201PortType")]
    public interface GetOrganization20111201PortType
    {
        
        // CODEGEN: Generating message contract since the operation GetOrganization20111201Operation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="https://service.sd.dk/sdws/services/GetOrganization20111201", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GetOrganization.GetOrganization20111201OperationResponse GetOrganization20111201Operation(GetOrganization.GetOrganization20111201OperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.sd.dk/sdws/services/GetOrganization20111201", ReplyAction="*")]
        System.Threading.Tasks.Task<GetOrganization.GetOrganization20111201OperationResponse> GetOrganization20111201OperationAsync(GetOrganization.GetOrganization20111201OperationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class GetOrganizationRequestType
    {
        
        private string institutionIdentifierField;
        
        private string institutionUUIDIdentifierField;
        
        private System.DateTime activationDateField;
        
        private System.DateTime deactivationDateField;
        
        private bool uUIDIndicatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string InstitutionIdentifier
        {
            get
            {
                return this.institutionIdentifierField;
            }
            set
            {
                this.institutionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InstitutionUUIDIdentifier
        {
            get
            {
                return this.institutionUUIDIdentifierField;
            }
            set
            {
                this.institutionUUIDIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", DataType="date", Order=2)]
        public System.DateTime ActivationDate
        {
            get
            {
                return this.activationDateField;
            }
            set
            {
                this.activationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", DataType="date", Order=3)]
        public System.DateTime DeactivationDate
        {
            get
            {
                return this.deactivationDateField;
            }
            set
            {
                this.deactivationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool UUIDIndicator
        {
            get
            {
                return this.uUIDIndicatorField;
            }
            set
            {
                this.uUIDIndicatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class DepartmentReferenceType
    {
        
        private string departmentIdentifierField;
        
        private string departmentUUIDIdentifierField;
        
        private string departmentLevelIdentifierField;
        
        private DepartmentReferenceType[] departmentReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DepartmentIdentifier
        {
            get
            {
                return this.departmentIdentifierField;
            }
            set
            {
                this.departmentIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DepartmentUUIDIdentifier
        {
            get
            {
                return this.departmentUUIDIdentifierField;
            }
            set
            {
                this.departmentUUIDIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20080201/", Order=2)]
        public string DepartmentLevelIdentifier
        {
            get
            {
                return this.departmentLevelIdentifierField;
            }
            set
            {
                this.departmentLevelIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DepartmentReference", Order=3)]
        public DepartmentReferenceType[] DepartmentReference
        {
            get
            {
                return this.departmentReferenceField;
            }
            set
            {
                this.departmentReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class OrganizationType
    {
        
        private System.DateTime activationDateField;
        
        private System.DateTime deactivationDateField;
        
        private DepartmentReferenceType[] departmentReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", DataType="date", Order=0)]
        public System.DateTime ActivationDate
        {
            get
            {
                return this.activationDateField;
            }
            set
            {
                this.activationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", DataType="date", Order=1)]
        public System.DateTime DeactivationDate
        {
            get
            {
                return this.deactivationDateField;
            }
            set
            {
                this.deactivationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DepartmentReference", Order=2)]
        public DepartmentReferenceType[] DepartmentReference
        {
            get
            {
                return this.departmentReferenceField;
            }
            set
            {
                this.departmentReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20080201/")]
    public partial class DepartmentLevelReferenceType
    {
        
        private string departmentLevelIdentifierField;
        
        private DepartmentLevelReferenceType departmentLevelReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DepartmentLevelIdentifier
        {
            get
            {
                return this.departmentLevelIdentifierField;
            }
            set
            {
                this.departmentLevelIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DepartmentLevelReferenceType DepartmentLevelReference
        {
            get
            {
                return this.departmentLevelReferenceField;
            }
            set
            {
                this.departmentLevelReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20080201/")]
    public partial class OrganizationStructureType
    {
        
        private DepartmentLevelReferenceType departmentLevelReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DepartmentLevelReferenceType DepartmentLevelReference
        {
            get
            {
                return this.departmentLevelReferenceField;
            }
            set
            {
                this.departmentLevelReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class GetOrganization20111201Type
    {
        
        private GetOrganizationRequestType requestStructureField;
        
        private string regionIdentifierField;
        
        private string regionUUIDIdentifierField;
        
        private string institutionIdentifierField;
        
        private string institutionUUIDIdentifierField;
        
        private string departmentStructureNameField;
        
        private OrganizationStructureType organizationStructureField;
        
        private OrganizationType[] organizationField;
        
        private System.DateTime creationDateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public GetOrganizationRequestType RequestStructure
        {
            get
            {
                return this.requestStructureField;
            }
            set
            {
                this.requestStructureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RegionIdentifier
        {
            get
            {
                return this.regionIdentifierField;
            }
            set
            {
                this.regionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RegionUUIDIdentifier
        {
            get
            {
                return this.regionUUIDIdentifierField;
            }
            set
            {
                this.regionUUIDIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string InstitutionIdentifier
        {
            get
            {
                return this.institutionIdentifierField;
            }
            set
            {
                this.institutionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string InstitutionUUIDIdentifier
        {
            get
            {
                return this.institutionUUIDIdentifierField;
            }
            set
            {
                this.institutionUUIDIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20080201/", Order=5)]
        public string DepartmentStructureName
        {
            get
            {
                return this.departmentStructureNameField;
            }
            set
            {
                this.departmentStructureNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20080201/", Order=6)]
        public OrganizationStructureType OrganizationStructure
        {
            get
            {
                return this.organizationStructureField;
            }
            set
            {
                this.organizationStructureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Organization", Order=7)]
        public OrganizationType[] Organization
        {
            get
            {
                return this.organizationField;
            }
            set
            {
                this.organizationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime creationDateTime
        {
            get
            {
                return this.creationDateTimeField;
            }
            set
            {
                this.creationDateTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrganization20111201OperationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01", Order=0)]
        public GetOrganization.GetOrganizationRequestType GetOrganization;
        
        public GetOrganization20111201OperationRequest()
        {
        }
        
        public GetOrganization20111201OperationRequest(GetOrganization.GetOrganizationRequestType GetOrganization)
        {
            this.GetOrganization = GetOrganization;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrganization20111201OperationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01", Order=0)]
        public GetOrganization.GetOrganization20111201Type GetOrganization20111201;
        
        public GetOrganization20111201OperationResponse()
        {
        }
        
        public GetOrganization20111201OperationResponse(GetOrganization.GetOrganization20111201Type GetOrganization20111201)
        {
            this.GetOrganization20111201 = GetOrganization20111201;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface GetOrganization20111201PortTypeChannel : GetOrganization.GetOrganization20111201PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class GetOrganization20111201PortTypeClient : System.ServiceModel.ClientBase<GetOrganization.GetOrganization20111201PortType>, GetOrganization.GetOrganization20111201PortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GetOrganization20111201PortTypeClient() : 
                base(GetOrganization20111201PortTypeClient.GetDefaultBinding(), GetOrganization20111201PortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.GetOrganization20111201.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetOrganization20111201PortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(GetOrganization20111201PortTypeClient.GetBindingForEndpoint(endpointConfiguration), GetOrganization20111201PortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetOrganization20111201PortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GetOrganization20111201PortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetOrganization20111201PortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GetOrganization20111201PortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetOrganization20111201PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetOrganization.GetOrganization20111201OperationResponse GetOrganization.GetOrganization20111201PortType.GetOrganization20111201Operation(GetOrganization.GetOrganization20111201OperationRequest request)
        {
            return base.Channel.GetOrganization20111201Operation(request);
        }
        
        public GetOrganization.GetOrganization20111201Type GetOrganization20111201Operation(GetOrganization.GetOrganizationRequestType GetOrganization)
        {
            GetOrganization.GetOrganization20111201OperationRequest inValue = new GetOrganization.GetOrganization20111201OperationRequest();
            inValue.GetOrganization = GetOrganization;
            GetOrganization.GetOrganization20111201OperationResponse retVal = ((GetOrganization.GetOrganization20111201PortType)(this)).GetOrganization20111201Operation(inValue);
            return retVal.GetOrganization20111201;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetOrganization.GetOrganization20111201OperationResponse> GetOrganization.GetOrganization20111201PortType.GetOrganization20111201OperationAsync(GetOrganization.GetOrganization20111201OperationRequest request)
        {
            return base.Channel.GetOrganization20111201OperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetOrganization.GetOrganization20111201OperationResponse> GetOrganization20111201OperationAsync(GetOrganization.GetOrganizationRequestType GetOrganization)
        {
            GetOrganization.GetOrganization20111201OperationRequest inValue = new GetOrganization.GetOrganization20111201OperationRequest();
            inValue.GetOrganization = GetOrganization;
            return ((GetOrganization.GetOrganization20111201PortType)(this)).GetOrganization20111201OperationAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GetOrganization20111201))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GetOrganization20111201))
            {
                return new System.ServiceModel.EndpointAddress("https://service.sd.dk/sdws/services/GetOrganization20111201");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GetOrganization20111201PortTypeClient.GetBindingForEndpoint(EndpointConfiguration.GetOrganization20111201);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GetOrganization20111201PortTypeClient.GetEndpointAddress(EndpointConfiguration.GetOrganization20111201);
        }
        
        public enum EndpointConfiguration
        {
            
            GetOrganization20111201,
        }
    }
}
