//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
namespace DigitalIdentity.SDMOX.Model
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:organisation:organisationenhed:2.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("OrganisationEnhed", Namespace = "urn:oio:sagdok:organisation:organisationenhed:2.0.0", IsNullable = false)]
    public partial class OrganisationEnhedType : AktoerType
    {

        private RegistreringType1[] registreringField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Registrering")]
        public RegistreringType1[] Registrering
        {
            get
            {
                return this.registreringField;
            }
            set
            {
                this.registreringField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "RegistreringType", Namespace = "urn:oio:sagdok:organisation:organisationenhed:2.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("Registrering", Namespace = "urn:oio:sagdok:organisation:organisationenhed:2.0.0", IsNullable = false)]
    public partial class RegistreringType1 : RegistreringType
    {

        private AttributListeType attributListeField;

        private TilstandListeType tilstandListeField;

        private RelationListeType relationListeField;

        /// <remarks/>
        public AttributListeType AttributListe
        {
            get
            {
                return this.attributListeField;
            }
            set
            {
                this.attributListeField = value;
            }
        }

        /// <remarks/>
        public TilstandListeType TilstandListe
        {
            get
            {
                return this.tilstandListeField;
            }
            set
            {
                this.tilstandListeField = value;
            }
        }

        /// <remarks/>
        public RelationListeType RelationListe
        {
            get
            {
                return this.relationListeField;
            }
            set
            {
                this.relationListeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:organisation:organisationenhed:2.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("AttributListe", Namespace = "urn:oio:sagdok:organisation:organisationenhed:2.0.0", IsNullable = false)]
    public partial class AttributListeType
    {

        private EgenskabType[] egenskabField;

        private LokalUdvidelseType lokalUdvidelseField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Egenskab")]
        public EgenskabType[] Egenskab
        {
            get
            {
                return this.egenskabField;
            }
            set
            {
                this.egenskabField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
        public LokalUdvidelseType LokalUdvidelse
        {
            get
            {
                return this.lokalUdvidelseField;
            }
            set
            {
                this.lokalUdvidelseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:organisation:organisationenhed:2.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("Egenskab", Namespace = "urn:oio:sagdok:organisation:organisationenhed:2.0.0", IsNullable = false)]
    public partial class EgenskabType
    {

        private string brugervendtNoegleTekstField;

        private string enhedNavnField;

        private VirkningType virkningField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
        public string BrugervendtNoegleTekst
        {
            get
            {
                return this.brugervendtNoegleTekstField;
            }
            set
            {
                this.brugervendtNoegleTekstField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
        public string EnhedNavn
        {
            get
            {
                return this.enhedNavnField;
            }
            set
            {
                this.enhedNavnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
        public VirkningType Virkning
        {
            get
            {
                return this.virkningField;
            }
            set
            {
                this.virkningField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("Virkning", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class VirkningType
    {

        private TidspunktType fraTidspunktField;

        private TidspunktType tilTidspunktField;

        private UnikIdType aktoerRefField;

        private AktoerTypeKodeType aktoerTypeKodeField;

        private bool aktoerTypeKodeFieldSpecified;

        private string noteTekstField;

        /// <remarks/>
        public TidspunktType FraTidspunkt
        {
            get
            {
                return this.fraTidspunktField;
            }
            set
            {
                this.fraTidspunktField = value;
            }
        }

        /// <remarks/>
        public TidspunktType TilTidspunkt
        {
            get
            {
                return this.tilTidspunktField;
            }
            set
            {
                this.tilTidspunktField = value;
            }
        }

        /// <remarks/>
        public UnikIdType AktoerRef
        {
            get
            {
                return this.aktoerRefField;
            }
            set
            {
                this.aktoerRefField = value;
            }
        }

        /// <remarks/>
        public AktoerTypeKodeType AktoerTypeKode
        {
            get
            {
                return this.aktoerTypeKodeField;
            }
            set
            {
                this.aktoerTypeKodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AktoerTypeKodeSpecified
        {
            get
            {
                return this.aktoerTypeKodeFieldSpecified;
            }
            set
            {
                this.aktoerTypeKodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("VirkningFraFilter", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class TidspunktType
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GraenseIndikator", typeof(bool))]
        [System.Xml.Serialization.XmlElementAttribute("TidsstempelDatoTid", typeof(System.DateTime))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KlassifikationRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FacetRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DokumentRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SagRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArkivRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AktoerRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganisationRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VirksomhedRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganisationEnhedRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MyndighedRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KlasseRelationType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("Relation", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class RelationType
    {

        private VirkningType virkningField;

        private UnikIdType referenceIDField;

        /// <remarks/>
        public VirkningType Virkning
        {
            get
            {
                return this.virkningField;
            }
            set
            {
                this.virkningField = value;
            }
        }

        /// <remarks/>
        public UnikIdType ReferenceID
        {
            get
            {
                return this.referenceIDField;
            }
            set
            {
                this.referenceIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("BrugerRef", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class UnikIdType
    {

        private string itemField;

        private ItemChoiceType itemElementNameField;

        private string identifikatorTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("URNIdentifikator", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("UUIDIdentifikator", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }

        /// <remarks/>
        public string IdentifikatorType
        {
            get
            {
                return this.identifikatorTypeField;
            }
            set
            {
                this.identifikatorTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0", IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        URNIdentifikator,

        /// <remarks/>
        UUIDIdentifikator,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("Facettilhoer", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class KlassifikationRelationType : RelationType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("Facet", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class FacetRelationType : RelationType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("NyRevision", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class DokumentRelationType : RelationType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("Praecedens", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class SagRelationType : RelationType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("Arkiv", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class ArkivRelationType : RelationType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("Ansvarlig", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class AktoerRelationType : RelationType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("Tilhoerer", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class OrganisationRelationType : RelationType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("Produktionsenhed", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class VirksomhedRelationType : RelationType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("Overordnet", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class OrganisationEnhedRelationType : RelationType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("Myndighed", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class MyndighedRelationType : RelationType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("Branche", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class KlasseRelationType : RelationType
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArkivFlerRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DokumentFlerRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PartFlerRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SagFlerRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AktoerFlerRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItSystemFlerRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganisationFlerRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InteressefaellesskabFlerRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganisationFunktionFlerRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganisationEnhedFlerRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BrugerFlerRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KlasseFlerRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonFlerRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdresseFlerRelationType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("FlerRelation", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class FlerRelationType
    {

        private VirkningType virkningField;

        private UnikIdType referenceIDField;

        /// <remarks/>
        public VirkningType Virkning
        {
            get
            {
                return this.virkningField;
            }
            set
            {
                this.virkningField = value;
            }
        }

        /// <remarks/>
        public UnikIdType ReferenceID
        {
            get
            {
                return this.referenceIDField;
            }
            set
            {
                this.referenceIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("Arkiver", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class ArkivFlerRelationType : FlerRelationType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("AndreDokumenter", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class DokumentFlerRelationType : FlerRelationType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("Parter", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class PartFlerRelationType : FlerRelationType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("AndreSager", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class SagFlerRelationType : FlerRelationType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("AndreBehandlere", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class AktoerFlerRelationType : FlerRelationType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("TilknyttedeItSystemer", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class ItSystemFlerRelationType : FlerRelationType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("TilknyttedeOrganisationer", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class OrganisationFlerRelationType : FlerRelationType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("TilknyttedeInteressefaellesskaber", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class InteressefaellesskabFlerRelationType : FlerRelationType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("TilknyttedeFunktioner", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class OrganisationFunktionFlerRelationType : FlerRelationType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("TilknyttedeEnheder", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class OrganisationEnhedFlerRelationType : FlerRelationType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("TilknyttedeBrugere", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class BrugerFlerRelationType : FlerRelationType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("Opgaver", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class KlasseFlerRelationType : FlerRelationType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("Ansatte", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class PersonFlerRelationType : FlerRelationType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("Adresser", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class AdresseFlerRelationType : FlerRelationType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:organisation:2.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("Gyldighed", Namespace = "urn:oio:sagdok:organisation:2.0.0", IsNullable = false)]
    public partial class GyldighedType
    {

        private VirkningType virkningField;

        private GyldighedStatusKodeType gyldighedStatusKodeField;

        private bool gyldighedStatusKodeFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
        public VirkningType Virkning
        {
            get
            {
                return this.virkningField;
            }
            set
            {
                this.virkningField = value;
            }
        }

        /// <remarks/>
        public GyldighedStatusKodeType GyldighedStatusKode
        {
            get
            {
                return this.gyldighedStatusKodeField;
            }
            set
            {
                this.gyldighedStatusKodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GyldighedStatusKodeSpecified
        {
            get
            {
                return this.gyldighedStatusKodeFieldSpecified;
            }
            set
            {
                this.gyldighedStatusKodeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:organisation:2.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("GyldighedStatusKode", Namespace = "urn:oio:sagdok:organisation:2.0.0", IsNullable = false)]
    public enum GyldighedStatusKodeType
    {

        /// <remarks/>
        Aktiv,

        /// <remarks/>
        Inaktiv,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("LokalUdvidelse", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class LokalUdvidelseType
    {

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistreringType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("Registrering", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class RegistreringType
    {

        private TidspunktType fraTidspunktField;

        private LivscyklusKodeType livscyklusKodeField;

        private UnikIdType brugerRefField;

        /// <remarks/>
        public TidspunktType FraTidspunkt
        {
            get
            {
                return this.fraTidspunktField;
            }
            set
            {
                this.fraTidspunktField = value;
            }
        }

        /// <remarks/>
        public LivscyklusKodeType LivscyklusKode
        {
            get
            {
                return this.livscyklusKodeField;
            }
            set
            {
                this.livscyklusKodeField = value;
            }
        }

        /// <remarks/>
        public UnikIdType BrugerRef
        {
            get
            {
                return this.brugerRefField;
            }
            set
            {
                this.brugerRefField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("LivscyklusKode", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public enum LivscyklusKodeType
    {

        /// <remarks/>
        Opstaaet,

        /// <remarks/>
        Importeret,

        /// <remarks/>
        Passiveret,

        /// <remarks/>
        Slettet,

        /// <remarks/>
        Rettet,

        /// <remarks/>
        Flyttet,
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LaesFiltreretOutputType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PartType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AktoerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganisationEnhedType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("SagDokObjekt", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class SagDokObjektType
    {

        private string uUIDIdentifikatorField;

        /// <remarks/>
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("LaesFiltreretOutput", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class LaesFiltreretOutputType : SagDokObjektType
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AktoerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganisationEnhedType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:part:1.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("Part", Namespace = "urn:oio:sagdok:part:1.0.0", IsNullable = false)]
    public partial class PartType : SagDokObjektType
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganisationEnhedType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:organisation:2.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("Aktoer", Namespace = "urn:oio:sagdok:organisation:2.0.0", IsNullable = false)]
    public partial class AktoerType : PartType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("AktoerTypeKode", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public enum AktoerTypeKodeType
    {

        /// <remarks/>
        Organisation,

        /// <remarks/>
        OrganisationEnhed,

        /// <remarks/>
        OrganisationFunktion,

        /// <remarks/>
        Bruger,

        /// <remarks/>
        ItSystem,

        /// <remarks/>
        Interessefaellesskab,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:organisation:organisationenhed:2.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("TilstandListe", Namespace = "urn:oio:sagdok:organisation:organisationenhed:2.0.0", IsNullable = false)]
    public partial class TilstandListeType
    {

        private GyldighedType[] gyldighedField;

        private LokalUdvidelseType lokalUdvidelseField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Gyldighed", Namespace = "urn:oio:sagdok:organisation:2.0.0")]
        public GyldighedType[] Gyldighed
        {
            get
            {
                return this.gyldighedField;
            }
            set
            {
                this.gyldighedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
        public LokalUdvidelseType LokalUdvidelse
        {
            get
            {
                return this.lokalUdvidelseField;
            }
            set
            {
                this.lokalUdvidelseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:organisation:organisationenhed:2.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("RelationListe", Namespace = "urn:oio:sagdok:organisation:organisationenhed:2.0.0", IsNullable = false)]
    public partial class RelationListeType
    {

        private AdresseFlerRelationType[] adresserField;

        private PersonFlerRelationType[] ansatteField;

        private KlasseRelationType[] brancheField;

        private KlasseRelationType[] enhedstypeField;

        private KlasseFlerRelationType[] opgaverField;

        private OrganisationEnhedRelationType[] overordnetField;

        private VirksomhedRelationType[] produktionsenhedField;

        private VirksomhedRelationType[] skatteenhedField;

        private OrganisationRelationType[] tilhoererField;

        private BrugerFlerRelationType[] tilknyttedeBrugereField;

        private OrganisationEnhedFlerRelationType[] tilknyttedeEnhederField;

        private OrganisationFunktionFlerRelationType[] tilknyttedeFunktionerField;

        private InteressefaellesskabFlerRelationType[] tilknyttedeInteressefaellesskaberField;

        private OrganisationFlerRelationType[] tilknyttedeOrganisationerField;

        private PersonFlerRelationType[] tilknyttedePersonerField;

        private ItSystemFlerRelationType[] tilknyttedeItSystemerField;

        private LokalUdvidelseType lokalUdvidelseField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Adresser", Namespace = "urn:oio:sagdok:3.0.0")]
        public AdresseFlerRelationType[] Adresser
        {
            get
            {
                return this.adresserField;
            }
            set
            {
                this.adresserField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ansatte", Namespace = "urn:oio:sagdok:3.0.0")]
        public PersonFlerRelationType[] Ansatte
        {
            get
            {
                return this.ansatteField;
            }
            set
            {
                this.ansatteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Branche", Namespace = "urn:oio:sagdok:3.0.0")]
        public KlasseRelationType[] Branche
        {
            get
            {
                return this.brancheField;
            }
            set
            {
                this.brancheField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Enhedstype", Namespace = "urn:oio:sagdok:3.0.0")]
        public KlasseRelationType[] Enhedstype
        {
            get
            {
                return this.enhedstypeField;
            }
            set
            {
                this.enhedstypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Opgaver", Namespace = "urn:oio:sagdok:3.0.0")]
        public KlasseFlerRelationType[] Opgaver
        {
            get
            {
                return this.opgaverField;
            }
            set
            {
                this.opgaverField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Overordnet", Namespace = "urn:oio:sagdok:3.0.0")]
        public OrganisationEnhedRelationType[] Overordnet
        {
            get
            {
                return this.overordnetField;
            }
            set
            {
                this.overordnetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Produktionsenhed", Namespace = "urn:oio:sagdok:3.0.0")]
        public VirksomhedRelationType[] Produktionsenhed
        {
            get
            {
                return this.produktionsenhedField;
            }
            set
            {
                this.produktionsenhedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Skatteenhed", Namespace = "urn:oio:sagdok:3.0.0")]
        public VirksomhedRelationType[] Skatteenhed
        {
            get
            {
                return this.skatteenhedField;
            }
            set
            {
                this.skatteenhedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Tilhoerer", Namespace = "urn:oio:sagdok:3.0.0")]
        public OrganisationRelationType[] Tilhoerer
        {
            get
            {
                return this.tilhoererField;
            }
            set
            {
                this.tilhoererField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TilknyttedeBrugere", Namespace = "urn:oio:sagdok:3.0.0")]
        public BrugerFlerRelationType[] TilknyttedeBrugere
        {
            get
            {
                return this.tilknyttedeBrugereField;
            }
            set
            {
                this.tilknyttedeBrugereField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TilknyttedeEnheder", Namespace = "urn:oio:sagdok:3.0.0")]
        public OrganisationEnhedFlerRelationType[] TilknyttedeEnheder
        {
            get
            {
                return this.tilknyttedeEnhederField;
            }
            set
            {
                this.tilknyttedeEnhederField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TilknyttedeFunktioner", Namespace = "urn:oio:sagdok:3.0.0")]
        public OrganisationFunktionFlerRelationType[] TilknyttedeFunktioner
        {
            get
            {
                return this.tilknyttedeFunktionerField;
            }
            set
            {
                this.tilknyttedeFunktionerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TilknyttedeInteressefaellesskaber", Namespace = "urn:oio:sagdok:3.0.0")]
        public InteressefaellesskabFlerRelationType[] TilknyttedeInteressefaellesskaber
        {
            get
            {
                return this.tilknyttedeInteressefaellesskaberField;
            }
            set
            {
                this.tilknyttedeInteressefaellesskaberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TilknyttedeOrganisationer", Namespace = "urn:oio:sagdok:3.0.0")]
        public OrganisationFlerRelationType[] TilknyttedeOrganisationer
        {
            get
            {
                return this.tilknyttedeOrganisationerField;
            }
            set
            {
                this.tilknyttedeOrganisationerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TilknyttedePersoner", Namespace = "urn:oio:sagdok:3.0.0")]
        public PersonFlerRelationType[] TilknyttedePersoner
        {
            get
            {
                return this.tilknyttedePersonerField;
            }
            set
            {
                this.tilknyttedePersonerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TilknyttedeItSystemer", Namespace = "urn:oio:sagdok:3.0.0")]
        public ItSystemFlerRelationType[] TilknyttedeItSystemer
        {
            get
            {
                return this.tilknyttedeItSystemerField;
            }
            set
            {
                this.tilknyttedeItSystemerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
        public LokalUdvidelseType LokalUdvidelse
        {
            get
            {
                return this.lokalUdvidelseField;
            }
            set
            {
                this.lokalUdvidelseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:organisation:organisationenhed:2.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("RegistreringBesked", Namespace = "urn:oio:sagdok:organisation:organisationenhed:2.0.0", IsNullable = false)]
    public partial class RegistreringBeskedType
    {

        private UnikIdType objektIDField;

        private RegistreringType1 registreringField;

        /// <remarks/>
        public UnikIdType ObjektID
        {
            get
            {
                return this.objektIDField;
            }
            set
            {
                this.objektIDField = value;
            }
        }

        /// <remarks/>
        public RegistreringType1 Registrering
        {
            get
            {
                return this.registreringField;
            }
            set
            {
                this.registreringField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:organisation:2.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("SoegGyldighed", Namespace = "urn:oio:sagdok:organisation:2.0.0", IsNullable = false)]
    public partial class SoegGyldighedType
    {

        private GyldighedStatusKodeType gyldighedStatusKodeField;

        private bool gyldighedStatusKodeFieldSpecified;

        private SoegVirkningType soegVirkningField;

        /// <remarks/>
        public GyldighedStatusKodeType GyldighedStatusKode
        {
            get
            {
                return this.gyldighedStatusKodeField;
            }
            set
            {
                this.gyldighedStatusKodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GyldighedStatusKodeSpecified
        {
            get
            {
                return this.gyldighedStatusKodeFieldSpecified;
            }
            set
            {
                this.gyldighedStatusKodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
        public SoegVirkningType SoegVirkning
        {
            get
            {
                return this.soegVirkningField;
            }
            set
            {
                this.soegVirkningField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("SoegVirkning", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class SoegVirkningType
    {

        private TidspunktType fraTidspunktField;

        private TidspunktType tilTidspunktField;

        private UnikIdType aktoerRefField;

        private AktoerTypeKodeType aktoerTypeKodeField;

        private bool aktoerTypeKodeFieldSpecified;

        private string noteTekstField;

        /// <remarks/>
        public TidspunktType FraTidspunkt
        {
            get
            {
                return this.fraTidspunktField;
            }
            set
            {
                this.fraTidspunktField = value;
            }
        }

        /// <remarks/>
        public TidspunktType TilTidspunkt
        {
            get
            {
                return this.tilTidspunktField;
            }
            set
            {
                this.tilTidspunktField = value;
            }
        }

        /// <remarks/>
        public UnikIdType AktoerRef
        {
            get
            {
                return this.aktoerRefField;
            }
            set
            {
                this.aktoerRefField = value;
            }
        }

        /// <remarks/>
        public AktoerTypeKodeType AktoerTypeKode
        {
            get
            {
                return this.aktoerTypeKodeField;
            }
            set
            {
                this.aktoerTypeKodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AktoerTypeKodeSpecified
        {
            get
            {
                return this.aktoerTypeKodeFieldSpecified;
            }
            set
            {
                this.aktoerTypeKodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("ImportInput", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class ImportInputType
    {

        private string noteTekstField;

        /// <remarks/>
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("UuidNoteInput", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class UuidNoteInputType
    {

        private string uUIDIdentifikatorField;

        private string noteTekstField;

        /// <remarks/>
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }

        /// <remarks/>
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("OpretInput", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class OpretInputType
    {

        private string noteTekstField;

        /// <remarks/>
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("BasicOutput", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class BasicOutputType
    {

        private StandardReturType standardReturField;

        /// <remarks/>
        public StandardReturType StandardRetur
        {
            get
            {
                return this.standardReturField;
            }
            set
            {
                this.standardReturField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("StandardRetur", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class StandardReturType
    {

        private string statusKodeField;

        private string fejlbeskedTekstField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string StatusKode
        {
            get
            {
                return this.statusKodeField;
            }
            set
            {
                this.statusKodeField = value;
            }
        }

        /// <remarks/>
        public string FejlbeskedTekst
        {
            get
            {
                return this.fejlbeskedTekstField;
            }
            set
            {
                this.fejlbeskedTekstField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("RetInput", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class RetInputType
    {

        private string uUIDIdentifikatorField;

        private string noteTekstField;

        /// <remarks/>
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }

        /// <remarks/>
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("LaesInput", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class LaesInputType
    {

        private string uUIDIdentifikatorField;

        private TidspunktType virkningFraFilterField;

        private TidspunktType virkningTilFilterField;

        private TidspunktType registreringFraFilterField;

        private TidspunktType registreringTilFilterField;

        /// <remarks/>
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }

        /// <remarks/>
        public TidspunktType VirkningFraFilter
        {
            get
            {
                return this.virkningFraFilterField;
            }
            set
            {
                this.virkningFraFilterField = value;
            }
        }

        /// <remarks/>
        public TidspunktType VirkningTilFilter
        {
            get
            {
                return this.virkningTilFilterField;
            }
            set
            {
                this.virkningTilFilterField = value;
            }
        }

        /// <remarks/>
        public TidspunktType RegistreringFraFilter
        {
            get
            {
                return this.registreringFraFilterField;
            }
            set
            {
                this.registreringFraFilterField = value;
            }
        }

        /// <remarks/>
        public TidspunktType RegistreringTilFilter
        {
            get
            {
                return this.registreringTilFilterField;
            }
            set
            {
                this.registreringTilFilterField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("ListInput", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class ListInputType
    {

        private string[] uUIDIdentifikatorField;

        private TidspunktType virkningFraFilterField;

        private TidspunktType virkningTilFilterField;

        private TidspunktType registreringFraFilterField;

        private TidspunktType registreringTilFilterField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UUIDIdentifikator")]
        public string[] UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }

        /// <remarks/>
        public TidspunktType VirkningFraFilter
        {
            get
            {
                return this.virkningFraFilterField;
            }
            set
            {
                this.virkningFraFilterField = value;
            }
        }

        /// <remarks/>
        public TidspunktType VirkningTilFilter
        {
            get
            {
                return this.virkningTilFilterField;
            }
            set
            {
                this.virkningTilFilterField = value;
            }
        }

        /// <remarks/>
        public TidspunktType RegistreringFraFilter
        {
            get
            {
                return this.registreringFraFilterField;
            }
            set
            {
                this.registreringFraFilterField = value;
            }
        }

        /// <remarks/>
        public TidspunktType RegistreringTilFilter
        {
            get
            {
                return this.registreringTilFilterField;
            }
            set
            {
                this.registreringTilFilterField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("ListOutput", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class ListOutputType
    {

        private StandardReturType standardReturField;

        /// <remarks/>
        public StandardReturType StandardRetur
        {
            get
            {
                return this.standardReturField;
            }
            set
            {
                this.standardReturField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("SoegInput", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class SoegInputType
    {

        private string foersteResultatReferenceField;

        private string maksimalAntalKvantitetField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string FoersteResultatReference
        {
            get
            {
                return this.foersteResultatReferenceField;
            }
            set
            {
                this.foersteResultatReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string MaksimalAntalKvantitet
        {
            get
            {
                return this.maksimalAntalKvantitetField;
            }
            set
            {
                this.maksimalAntalKvantitetField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("SoegOutput", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class SoegOutputType
    {

        private StandardReturType standardReturField;

        private string[] idListeField;

        /// <remarks/>
        public StandardReturType StandardRetur
        {
            get
            {
                return this.standardReturField;
            }
            set
            {
                this.standardReturField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("UUIDIdentifikator", IsNullable = false)]
        public string[] IdListe
        {
            get
            {
                return this.idListeField;
            }
            set
            {
                this.idListeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("SoegSagDokObjekt", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class SoegSagDokObjektType
    {

        private string uUIDIdentifikatorField;

        private SoegRegistreringType soegRegistreringField;

        private SoegVirkningType soegVirkningField;

        /// <remarks/>
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }

        /// <remarks/>
        public SoegRegistreringType SoegRegistrering
        {
            get
            {
                return this.soegRegistreringField;
            }
            set
            {
                this.soegRegistreringField = value;
            }
        }

        /// <remarks/>
        public SoegVirkningType SoegVirkning
        {
            get
            {
                return this.soegVirkningField;
            }
            set
            {
                this.soegVirkningField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("SoegRegistrering", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class SoegRegistreringType
    {

        private TidspunktType fraTidspunktField;

        private LivscyklusKodeType livscyklusKodeField;

        private bool livscyklusKodeFieldSpecified;

        private UnikIdType brugerRefField;

        /// <remarks/>
        public TidspunktType FraTidspunkt
        {
            get
            {
                return this.fraTidspunktField;
            }
            set
            {
                this.fraTidspunktField = value;
            }
        }

        /// <remarks/>
        public LivscyklusKodeType LivscyklusKode
        {
            get
            {
                return this.livscyklusKodeField;
            }
            set
            {
                this.livscyklusKodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LivscyklusKodeSpecified
        {
            get
            {
                return this.livscyklusKodeFieldSpecified;
            }
            set
            {
                this.livscyklusKodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public UnikIdType BrugerRef
        {
            get
            {
                return this.brugerRefField;
            }
            set
            {
                this.brugerRefField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("IdListe", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class IdListeType
    {

        private string[] uUIDIdentifikatorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UUIDIdentifikator")]
        public string[] UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoegJournalPostRelationType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("SoegAdresser", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class SoegRelationType
    {

        private SoegVirkningType soegVirkningField;

        private UnikIdType referenceIDField;

        /// <remarks/>
        public SoegVirkningType SoegVirkning
        {
            get
            {
                return this.soegVirkningField;
            }
            set
            {
                this.soegVirkningField = value;
            }
        }

        /// <remarks/>
        public UnikIdType ReferenceID
        {
            get
            {
                return this.referenceIDField;
            }
            set
            {
                this.referenceIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("JournalPoster", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class JournalPostFlerRelationType : NulFlerRelationType
    {

        private string journalPostIdentifikatorField;

        private string titelTekstField;

        private string indeksIdentifikatorField;

        private OffentlighedUndtagetType offentlighedUndtagetField;

        private TilhoersforholdKodeType tilhoersforholdKodeField;

        /// <remarks/>
        public string JournalPostIdentifikator
        {
            get
            {
                return this.journalPostIdentifikatorField;
            }
            set
            {
                this.journalPostIdentifikatorField = value;
            }
        }

        /// <remarks/>
        public string TitelTekst
        {
            get
            {
                return this.titelTekstField;
            }
            set
            {
                this.titelTekstField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string IndeksIdentifikator
        {
            get
            {
                return this.indeksIdentifikatorField;
            }
            set
            {
                this.indeksIdentifikatorField = value;
            }
        }

        /// <remarks/>
        public OffentlighedUndtagetType OffentlighedUndtaget
        {
            get
            {
                return this.offentlighedUndtagetField;
            }
            set
            {
                this.offentlighedUndtagetField = value;
            }
        }

        /// <remarks/>
        public TilhoersforholdKodeType TilhoersforholdKode
        {
            get
            {
                return this.tilhoersforholdKodeField;
            }
            set
            {
                this.tilhoersforholdKodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("OffentlighedUndtaget", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class OffentlighedUndtagetType
    {

        private string titelAlternativTekstField;

        private string offentlighedUndtagetHjemmelTekstField;

        /// <remarks/>
        public string TitelAlternativTekst
        {
            get
            {
                return this.titelAlternativTekstField;
            }
            set
            {
                this.titelAlternativTekstField = value;
            }
        }

        /// <remarks/>
        public string OffentlighedUndtagetHjemmelTekst
        {
            get
            {
                return this.offentlighedUndtagetHjemmelTekstField;
            }
            set
            {
                this.offentlighedUndtagetHjemmelTekstField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("TilhoersforholdKode", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public enum TilhoersforholdKodeType
    {

        /// <remarks/>
        Vedlagt,

        /// <remarks/>
        Tilakteret,
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JournalPostFlerRelationType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("NulFlerRelation", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class NulFlerRelationType
    {

        private VirkningType virkningField;

        private UnikIdType referenceIDField;

        /// <remarks/>
        public VirkningType Virkning
        {
            get
            {
                return this.virkningField;
            }
            set
            {
                this.virkningField = value;
            }
        }

        /// <remarks/>
        public UnikIdType ReferenceID
        {
            get
            {
                return this.referenceIDField;
            }
            set
            {
                this.referenceIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("SoegJournalPoster", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public partial class SoegJournalPostRelationType : SoegRelationType
    {

        private string journalPostIdentifikatorField;

        private string titelTekstField;

        private string indeksIdentifikatorField;

        private OffentlighedUndtagetType offentlighedUndtagetField;

        private TilhoersforholdKodeType tilhoersforholdKodeField;

        private bool tilhoersforholdKodeFieldSpecified;

        /// <remarks/>
        public string JournalPostIdentifikator
        {
            get
            {
                return this.journalPostIdentifikatorField;
            }
            set
            {
                this.journalPostIdentifikatorField = value;
            }
        }

        /// <remarks/>
        public string TitelTekst
        {
            get
            {
                return this.titelTekstField;
            }
            set
            {
                this.titelTekstField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string IndeksIdentifikator
        {
            get
            {
                return this.indeksIdentifikatorField;
            }
            set
            {
                this.indeksIdentifikatorField = value;
            }
        }

        /// <remarks/>
        public OffentlighedUndtagetType OffentlighedUndtaget
        {
            get
            {
                return this.offentlighedUndtagetField;
            }
            set
            {
                this.offentlighedUndtagetField = value;
            }
        }

        /// <remarks/>
        public TilhoersforholdKodeType TilhoersforholdKode
        {
            get
            {
                return this.tilhoersforholdKodeField;
            }
            set
            {
                this.tilhoersforholdKodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TilhoersforholdKodeSpecified
        {
            get
            {
                return this.tilhoersforholdKodeFieldSpecified;
            }
            set
            {
                this.tilhoersforholdKodeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("ArkivTypeKode", Namespace = "urn:oio:sagdok:3.0.0", IsNullable = false)]
    public enum ArkivTypeKodeType
    {

        /// <remarks/>
        Forvaltning,

        /// <remarks/>
        Reference,

        /// <remarks/>
        Personlig,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:silkdata:1.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("Integration", Namespace = "urn:oio:silkdata:1.0.0", IsNullable = false)]
    public partial class IntegrationType
    {

        private VirkningType virkningField;

        private string attributNavnField;

        private string attributVaerdiField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
        public VirkningType Virkning
        {
            get
            {
                return this.virkningField;
            }
            set
            {
                this.virkningField = value;
            }
        }

        /// <remarks/>
        public string AttributNavn
        {
            get
            {
                return this.attributNavnField;
            }
            set
            {
                this.attributNavnField = value;
            }
        }

        /// <remarks/>
        public string AttributVaerdi
        {
            get
            {
                return this.attributVaerdiField;
            }
            set
            {
                this.attributVaerdiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:silkdata:1.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("Lokation", Namespace = "urn:oio:silkdata:1.0.0", IsNullable = false)]
    public partial class LokationType
    {

        private ProduktionEnhedType produktionEnhedField;

        private KontaktType kontaktField;

        private DanskAdresseType danskAdresseField;

        /// <remarks/>
        public ProduktionEnhedType ProduktionEnhed
        {
            get
            {
                return this.produktionEnhedField;
            }
            set
            {
                this.produktionEnhedField = value;
            }
        }

        /// <remarks/>
        public KontaktType Kontakt
        {
            get
            {
                return this.kontaktField;
            }
            set
            {
                this.kontaktField = value;
            }
        }

        /// <remarks/>
        public DanskAdresseType DanskAdresse
        {
            get
            {
                return this.danskAdresseField;
            }
            set
            {
                this.danskAdresseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:silkdata:1.0.0")]
    public partial class ProduktionEnhedType
    {

        private string uUIDIdentifikatorField;

        private VirkningType virkningField;

        private string produktionEnhedIdentifikatorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
        public VirkningType Virkning
        {
            get
            {
                return this.virkningField;
            }
            set
            {
                this.virkningField = value;
            }
        }

        /// <remarks/>
        public string ProduktionEnhedIdentifikator
        {
            get
            {
                return this.produktionEnhedIdentifikatorField;
            }
            set
            {
                this.produktionEnhedIdentifikatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:silkdata:1.0.0")]
    public partial class KontaktType
    {

        private string uUIDIdentifikatorField;

        private VirkningType virkningField;

        private string lokalTelefonnummerIdentifikatorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
        public VirkningType Virkning
        {
            get
            {
                return this.virkningField;
            }
            set
            {
                this.virkningField = value;
            }
        }

        /// <remarks/>
        public string LokalTelefonnummerIdentifikator
        {
            get
            {
                return this.lokalTelefonnummerIdentifikatorField;
            }
            set
            {
                this.lokalTelefonnummerIdentifikatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:silkdata:1.0.0")]
    public partial class DanskAdresseType
    {

        private string uUIDIdentifikatorField;

        private VirkningType virkningField;

        private string adresseNavnField;

        private string postKodeIdentifikatorField;

        private string byNavnField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
        public VirkningType Virkning
        {
            get
            {
                return this.virkningField;
            }
            set
            {
                this.virkningField = value;
            }
        }

        /// <remarks/>
        public string AdresseNavn
        {
            get
            {
                return this.adresseNavnField;
            }
            set
            {
                this.adresseNavnField = value;
            }
        }

        /// <remarks/>
        public string PostKodeIdentifikator
        {
            get
            {
                return this.postKodeIdentifikatorField;
            }
            set
            {
                this.postKodeIdentifikatorField = value;
            }
        }

        /// <remarks/>
        public string ByNavn
        {
            get
            {
                return this.byNavnField;
            }
            set
            {
                this.byNavnField = value;
            }
        }
    }
}
