
package https.wsieksport_unilogin_dk.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.3
 * 2021-11-10T07:46:49.897+01:00
 * Generated source version: 3.3.3
 */

@WebFault(name = "authentificationError", targetNamespace = "https://unilogin.dk")
public class AuthentificationFault extends Exception {

    private https.unilogin.AuthentificationError authentificationError;

    public AuthentificationFault() {
        super();
    }

    public AuthentificationFault(String message) {
        super(message);
    }

    public AuthentificationFault(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public AuthentificationFault(String message, https.unilogin.AuthentificationError authentificationError) {
        super(message);
        this.authentificationError = authentificationError;
    }

    public AuthentificationFault(String message, https.unilogin.AuthentificationError authentificationError, java.lang.Throwable cause) {
        super(message, cause);
        this.authentificationError = authentificationError;
    }

    public https.unilogin.AuthentificationError getFaultInfo() {
        return this.authentificationError;
    }
}
