//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetDepartment
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.sd.dk/sdws/GetDepartment20111201", ConfigurationName="GetDepartment.GetDepartment20111201PortType")]
    public interface GetDepartment20111201PortType
    {
        
        // CODEGEN: Generating message contract since the operation GetDepartment20111201Operation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="https://service.sd.dk/sdws/services/GetDepartment20111201", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GetDepartment.GetDepartment20111201OperationResponse GetDepartment20111201Operation(GetDepartment.GetDepartment20111201OperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.sd.dk/sdws/services/GetDepartment20111201", ReplyAction="*")]
        System.Threading.Tasks.Task<GetDepartment.GetDepartment20111201OperationResponse> GetDepartment20111201OperationAsync(GetDepartment.GetDepartment20111201OperationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class GetDepartmentRequestType
    {
        
        private string institutionIdentifierField;
        
        private string institutionUUIDIdentifierField;
        
        private string departmentIdentifierField;
        
        private string departmentLevelIdentifierField;
        
        private string departmentUUIDIdentifierField;
        
        private System.DateTime activationDateField;
        
        private System.DateTime deactivationDateField;
        
        private bool contactInformationIndicatorField;
        
        private bool departmentNameIndicatorField;
        
        private bool employmentDepartmentIndicatorField;
        
        private bool postalAddressIndicatorField;
        
        private bool productionUnitIndicatorField;
        
        private bool uUIDIndicatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string InstitutionIdentifier
        {
            get
            {
                return this.institutionIdentifierField;
            }
            set
            {
                this.institutionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InstitutionUUIDIdentifier
        {
            get
            {
                return this.institutionUUIDIdentifierField;
            }
            set
            {
                this.institutionUUIDIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DepartmentIdentifier
        {
            get
            {
                return this.departmentIdentifierField;
            }
            set
            {
                this.departmentIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20080201/", Order=3)]
        public string DepartmentLevelIdentifier
        {
            get
            {
                return this.departmentLevelIdentifierField;
            }
            set
            {
                this.departmentLevelIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DepartmentUUIDIdentifier
        {
            get
            {
                return this.departmentUUIDIdentifierField;
            }
            set
            {
                this.departmentUUIDIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", DataType="date", Order=5)]
        public System.DateTime ActivationDate
        {
            get
            {
                return this.activationDateField;
            }
            set
            {
                this.activationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", DataType="date", Order=6)]
        public System.DateTime DeactivationDate
        {
            get
            {
                return this.deactivationDateField;
            }
            set
            {
                this.deactivationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", Order=7)]
        public bool ContactInformationIndicator
        {
            get
            {
                return this.contactInformationIndicatorField;
            }
            set
            {
                this.contactInformationIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20080201/", Order=8)]
        public bool DepartmentNameIndicator
        {
            get
            {
                return this.departmentNameIndicatorField;
            }
            set
            {
                this.departmentNameIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool EmploymentDepartmentIndicator
        {
            get
            {
                return this.employmentDepartmentIndicatorField;
            }
            set
            {
                this.employmentDepartmentIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", Order=10)]
        public bool PostalAddressIndicator
        {
            get
            {
                return this.postalAddressIndicatorField;
            }
            set
            {
                this.postalAddressIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool ProductionUnitIndicator
        {
            get
            {
                return this.productionUnitIndicatorField;
            }
            set
            {
                this.productionUnitIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool UUIDIndicator
        {
            get
            {
                return this.uUIDIndicatorField;
            }
            set
            {
                this.uUIDIndicatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20080201/")]
    public partial class ContactInformationType
    {
        
        private string[] telephoneNumberIdentifierField;
        
        private string[] emailAddressIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TelephoneNumberIdentifier", Namespace="http://rep.oio.dk/itst.dk/xml/schemas/2005/01/10/", Order=0)]
        public string[] TelephoneNumberIdentifier
        {
            get
            {
                return this.telephoneNumberIdentifierField;
            }
            set
            {
                this.telephoneNumberIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EmailAddressIdentifier", Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2005/03/15/", Order=1)]
        public string[] EmailAddressIdentifier
        {
            get
            {
                return this.emailAddressIdentifierField;
            }
            set
            {
                this.emailAddressIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
    public partial class CountryIdentificationCodeType
    {
        
        private _CountryIdentificationSchemeType schemeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public _CountryIdentificationSchemeType scheme
        {
            get
            {
                return this.schemeField;
            }
            set
            {
                this.schemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
    public enum _CountryIdentificationSchemeType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("iso3166-alpha2")]
        iso3166alpha2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("iso3166-alpha3")]
        iso3166alpha3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("un-numeric3")]
        unnumeric3,
        
        /// <remarks/>
        imk,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/")]
    public partial class PostalAddressType
    {
        
        private string standardAddressIdentifierField;
        
        private string postalCodeField;
        
        private string districtNameField;
        
        private string municipalityCodeField;
        
        private CountryIdentificationCodeType countryIdentificationCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/itst.dk/xml/schemas/2005/06/24/", Order=0)]
        public string StandardAddressIdentifier
        {
            get
            {
                return this.standardAddressIdentifierField;
            }
            set
            {
                this.standardAddressIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/", Order=2)]
        public string DistrictName
        {
            get
            {
                return this.districtNameField;
            }
            set
            {
                this.districtNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/", Order=3)]
        public string MunicipalityCode
        {
            get
            {
                return this.municipalityCodeField;
            }
            set
            {
                this.municipalityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=4)]
        public CountryIdentificationCodeType CountryIdentificationCode
        {
            get
            {
                return this.countryIdentificationCodeField;
            }
            set
            {
                this.countryIdentificationCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class DepartmentType
    {
        
        private System.DateTime activationDateField;
        
        private System.DateTime deactivationDateField;
        
        private string departmentIdentifierField;
        
        private string departmentUUIDIdentifierField;
        
        private string departmentLevelIdentifierField;
        
        private string departmentNameField;
        
        private string productionUnitIdentifierField;
        
        private PostalAddressType postalAddressField;
        
        private ContactInformationType contactInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", DataType="date", Order=0)]
        public System.DateTime ActivationDate
        {
            get
            {
                return this.activationDateField;
            }
            set
            {
                this.activationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", DataType="date", Order=1)]
        public System.DateTime DeactivationDate
        {
            get
            {
                return this.deactivationDateField;
            }
            set
            {
                this.deactivationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DepartmentIdentifier
        {
            get
            {
                return this.departmentIdentifierField;
            }
            set
            {
                this.departmentIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DepartmentUUIDIdentifier
        {
            get
            {
                return this.departmentUUIDIdentifierField;
            }
            set
            {
                this.departmentUUIDIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20080201/", Order=4)]
        public string DepartmentLevelIdentifier
        {
            get
            {
                return this.departmentLevelIdentifierField;
            }
            set
            {
                this.departmentLevelIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20080201/", Order=5)]
        public string DepartmentName
        {
            get
            {
                return this.departmentNameField;
            }
            set
            {
                this.departmentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cvr.dk/xml/schemas/2005/03/22/", Order=6)]
        public string ProductionUnitIdentifier
        {
            get
            {
                return this.productionUnitIdentifierField;
            }
            set
            {
                this.productionUnitIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", Order=7)]
        public PostalAddressType PostalAddress
        {
            get
            {
                return this.postalAddressField;
            }
            set
            {
                this.postalAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20080201/", Order=8)]
        public ContactInformationType ContactInformation
        {
            get
            {
                return this.contactInformationField;
            }
            set
            {
                this.contactInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class GetDepartment20111201Type
    {
        
        private GetDepartmentRequestType requestStructureField;
        
        private string regionIdentifierField;
        
        private string regionUUIDIdentifierField;
        
        private string institutionIdentifierField;
        
        private string institutionUUIDIdentifierField;
        
        private DepartmentType[] departmentField;
        
        private System.DateTime creationDateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public GetDepartmentRequestType RequestStructure
        {
            get
            {
                return this.requestStructureField;
            }
            set
            {
                this.requestStructureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RegionIdentifier
        {
            get
            {
                return this.regionIdentifierField;
            }
            set
            {
                this.regionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RegionUUIDIdentifier
        {
            get
            {
                return this.regionUUIDIdentifierField;
            }
            set
            {
                this.regionUUIDIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string InstitutionIdentifier
        {
            get
            {
                return this.institutionIdentifierField;
            }
            set
            {
                this.institutionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string InstitutionUUIDIdentifier
        {
            get
            {
                return this.institutionUUIDIdentifierField;
            }
            set
            {
                this.institutionUUIDIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Department", Order=5)]
        public DepartmentType[] Department
        {
            get
            {
                return this.departmentField;
            }
            set
            {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime creationDateTime
        {
            get
            {
                return this.creationDateTimeField;
            }
            set
            {
                this.creationDateTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDepartment20111201OperationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01", Order=0)]
        public GetDepartment.GetDepartmentRequestType GetDepartment;
        
        public GetDepartment20111201OperationRequest()
        {
        }
        
        public GetDepartment20111201OperationRequest(GetDepartment.GetDepartmentRequestType GetDepartment)
        {
            this.GetDepartment = GetDepartment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDepartment20111201OperationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01", Order=0)]
        public GetDepartment.GetDepartment20111201Type GetDepartment20111201;
        
        public GetDepartment20111201OperationResponse()
        {
        }
        
        public GetDepartment20111201OperationResponse(GetDepartment.GetDepartment20111201Type GetDepartment20111201)
        {
            this.GetDepartment20111201 = GetDepartment20111201;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface GetDepartment20111201PortTypeChannel : GetDepartment.GetDepartment20111201PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class GetDepartment20111201PortTypeClient : System.ServiceModel.ClientBase<GetDepartment.GetDepartment20111201PortType>, GetDepartment.GetDepartment20111201PortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GetDepartment20111201PortTypeClient() : 
                base(GetDepartment20111201PortTypeClient.GetDefaultBinding(), GetDepartment20111201PortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.GetDepartment20111201.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetDepartment20111201PortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(GetDepartment20111201PortTypeClient.GetBindingForEndpoint(endpointConfiguration), GetDepartment20111201PortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetDepartment20111201PortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GetDepartment20111201PortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetDepartment20111201PortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GetDepartment20111201PortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetDepartment20111201PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetDepartment.GetDepartment20111201OperationResponse GetDepartment.GetDepartment20111201PortType.GetDepartment20111201Operation(GetDepartment.GetDepartment20111201OperationRequest request)
        {
            return base.Channel.GetDepartment20111201Operation(request);
        }
        
        public GetDepartment.GetDepartment20111201Type GetDepartment20111201Operation(GetDepartment.GetDepartmentRequestType GetDepartment)
        {
            GetDepartment.GetDepartment20111201OperationRequest inValue = new GetDepartment.GetDepartment20111201OperationRequest();
            inValue.GetDepartment = GetDepartment;
            GetDepartment.GetDepartment20111201OperationResponse retVal = ((GetDepartment.GetDepartment20111201PortType)(this)).GetDepartment20111201Operation(inValue);
            return retVal.GetDepartment20111201;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetDepartment.GetDepartment20111201OperationResponse> GetDepartment.GetDepartment20111201PortType.GetDepartment20111201OperationAsync(GetDepartment.GetDepartment20111201OperationRequest request)
        {
            return base.Channel.GetDepartment20111201OperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetDepartment.GetDepartment20111201OperationResponse> GetDepartment20111201OperationAsync(GetDepartment.GetDepartmentRequestType GetDepartment)
        {
            GetDepartment.GetDepartment20111201OperationRequest inValue = new GetDepartment.GetDepartment20111201OperationRequest();
            inValue.GetDepartment = GetDepartment;
            return ((GetDepartment.GetDepartment20111201PortType)(this)).GetDepartment20111201OperationAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GetDepartment20111201))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GetDepartment20111201))
            {
                return new System.ServiceModel.EndpointAddress("https://service.sd.dk/sdws/services/GetDepartment20111201");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GetDepartment20111201PortTypeClient.GetBindingForEndpoint(EndpointConfiguration.GetDepartment20111201);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GetDepartment20111201PortTypeClient.GetEndpointAddress(EndpointConfiguration.GetDepartment20111201);
        }
        
        public enum EndpointConfiguration
        {
            
            GetDepartment20111201,
        }
    }
}
