//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CprSubscriptionService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/", ConfigurationName="CprSubscriptionService.CprSubscriptionWebServicePortType")]
    public interface CprSubscriptionWebServicePortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CprSubscriptionService.AddPNRSubscriptionResponse> AddPNRSubscriptionAsync(CprSubscriptionService.AddPNRSubscriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CprSubscriptionService.RemovePNRSubscriptionResponse> RemovePNRSubscriptionAsync(CprSubscriptionService.RemovePNRSubscriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CprSubscriptionService.AddAgeRangeSubscriptionResponse> AddAgeRangeSubscriptionAsync(CprSubscriptionService.AddAgeRangeSubscriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CprSubscriptionService.RemoveAgeRangeSubscriptionResponse> RemoveAgeRangeSubscriptionAsync(CprSubscriptionService.RemoveAgeRangeSubscriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CprSubscriptionService.AddMunicipalityCodeSubscriptionResponse> AddMunicipalityCodeSubscriptionAsync(CprSubscriptionService.AddMunicipalityCodeSubscriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CprSubscriptionService.RemoveMunicipalityCodeSubscriptionResponse> RemoveMunicipalityCodeSubscriptionAsync(CprSubscriptionService.RemoveMunicipalityCodeSubscriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CprSubscriptionService.AddChangeCodeSubscriptionResponse> AddChangeCodeSubscriptionAsync(CprSubscriptionService.AddChangeCodeSubscriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CprSubscriptionService.RemoveChangeCodeSubscriptionResponse> RemoveChangeCodeSubscriptionAsync(CprSubscriptionService.RemoveChangeCodeSubscriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CprSubscriptionService.AddNoFilterSubscriptionResponse> AddNoFilterSubscriptionAsync(CprSubscriptionService.AddNoFilterSubscriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CprSubscriptionService.RemoveNoFilterSubscriptionResponse> RemoveNoFilterSubscriptionAsync(CprSubscriptionService.RemoveNoFilterSubscriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CprSubscriptionService.RemoveAllResponse> RemoveAllAsync(CprSubscriptionService.RemoveAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CprSubscriptionService.GetAllFiltersResponse> GetAllFiltersAsync(CprSubscriptionService.GetAllFiltersRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public partial class AddPNRSubscriptionType
    {
        
        private InvocationContextType invocationContextField;
        
        private string pNRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://serviceplatformen.dk/xml/schemas/InvocationContext/1/", Order=0)]
        public InvocationContextType InvocationContext
        {
            get
            {
                return this.invocationContextField;
            }
            set
            {
                this.invocationContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://serviceplatformen.dk/xml/schemas/cpr/PNR/1/", Order=1)]
        public string PNR
        {
            get
            {
                return this.pNRField;
            }
            set
            {
                this.pNRField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/schemas/InvocationContext/1/")]
    public partial class InvocationContextType
    {
        
        private string serviceAgreementUUIDField;
        
        private string userSystemUUIDField;
        
        private string userUUIDField;
        
        private string onBehalfOfUserField;
        
        private string serviceUUIDField;
        
        private string callersServiceCallIdentifierField;
        
        private string accountingInfoField;
        
        /// <remarks/>
        public string ServiceAgreementUUID
        {
            get
            {
                return this.serviceAgreementUUIDField;
            }
            set
            {
                this.serviceAgreementUUIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserSystemUUID
        {
            get
            {
                return this.userSystemUUIDField;
            }
            set
            {
                this.userSystemUUIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserUUID
        {
            get
            {
                return this.userUUIDField;
            }
            set
            {
                this.userUUIDField = value;
            }
        }
        
        /// <remarks/>
        public string OnBehalfOfUser
        {
            get
            {
                return this.onBehalfOfUserField;
            }
            set
            {
                this.onBehalfOfUserField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceUUID
        {
            get
            {
                return this.serviceUUIDField;
            }
            set
            {
                this.serviceUUIDField = value;
            }
        }
        
        /// <remarks/>
        public string CallersServiceCallIdentifier
        {
            get
            {
                return this.callersServiceCallIdentifierField;
            }
            set
            {
                this.callersServiceCallIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string AccountingInfo
        {
            get
            {
                return this.accountingInfoField;
            }
            set
            {
                this.accountingInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public partial class GetAllFiltersResponseType
    {
        
        private AgeRange[] ageRangeField;
        
        private string[] changeCodeField;
        
        private string[] municipalityCodeField;
        
        private string[] pNRField;
        
        private bool noFilterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AgeRange", Order=0)]
        public AgeRange[] AgeRange
        {
            get
            {
                return this.ageRangeField;
            }
            set
            {
                this.ageRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ChangeCode", Order=1)]
        public string[] ChangeCode
        {
            get
            {
                return this.changeCodeField;
            }
            set
            {
                this.changeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MunicipalityCode", DataType="nonNegativeInteger", Order=2)]
        public string[] MunicipalityCode
        {
            get
            {
                return this.municipalityCodeField;
            }
            set
            {
                this.municipalityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PNR", Namespace="http://serviceplatformen.dk/xml/schemas/cpr/PNR/1/", Order=3)]
        public string[] PNR
        {
            get
            {
                return this.pNRField;
            }
            set
            {
                this.pNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool noFilter
        {
            get
            {
                return this.noFilterField;
            }
            set
            {
                this.noFilterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public partial class AgeRange
    {
        
        private string startAgeField;
        
        private string endAgeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=0)]
        public string StartAge
        {
            get
            {
                return this.startAgeField;
            }
            set
            {
                this.startAgeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=1)]
        public string EndAge
        {
            get
            {
                return this.endAgeField;
            }
            set
            {
                this.endAgeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public partial class GetAllFiltersType
    {
        
        private InvocationContextType invocationContextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://serviceplatformen.dk/xml/schemas/InvocationContext/1/", Order=0)]
        public InvocationContextType InvocationContext
        {
            get
            {
                return this.invocationContextField;
            }
            set
            {
                this.invocationContextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public partial class RemoveAllResponseType
    {
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public partial class RemoveAllType
    {
        
        private InvocationContextType invocationContextField;
        
        private FilterGroup filterGroupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://serviceplatformen.dk/xml/schemas/InvocationContext/1/", Order=0)]
        public InvocationContextType InvocationContext
        {
            get
            {
                return this.invocationContextField;
            }
            set
            {
                this.invocationContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FilterGroup FilterGroup
        {
            get
            {
                return this.filterGroupField;
            }
            set
            {
                this.filterGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public enum FilterGroup
    {
        
        /// <remarks/>
        PNR,
        
        /// <remarks/>
        AgeRange,
        
        /// <remarks/>
        MunicipalityCode,
        
        /// <remarks/>
        EventChangeCode,
        
        /// <remarks/>
        NoFilter,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public partial class RemoveNoFilterSubscriptionResponseType
    {
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public partial class RemoveNoFilterSubscriptionType
    {
        
        private InvocationContextType invocationContextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://serviceplatformen.dk/xml/schemas/InvocationContext/1/", Order=0)]
        public InvocationContextType InvocationContext
        {
            get
            {
                return this.invocationContextField;
            }
            set
            {
                this.invocationContextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public partial class AddNoFilterSubscriptionResponseType
    {
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public partial class AddNoFilterSubscriptionType
    {
        
        private InvocationContextType invocationContextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://serviceplatformen.dk/xml/schemas/InvocationContext/1/", Order=0)]
        public InvocationContextType InvocationContext
        {
            get
            {
                return this.invocationContextField;
            }
            set
            {
                this.invocationContextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public partial class RemoveChangeCodeSubscriptionResponseType
    {
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public partial class RemoveChangeCodeSubscriptionType
    {
        
        private InvocationContextType invocationContextField;
        
        private string changeCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://serviceplatformen.dk/xml/schemas/InvocationContext/1/", Order=0)]
        public InvocationContextType InvocationContext
        {
            get
            {
                return this.invocationContextField;
            }
            set
            {
                this.invocationContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ChangeCode
        {
            get
            {
                return this.changeCodeField;
            }
            set
            {
                this.changeCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public partial class AddChangeCodeSubscriptionResponseType
    {
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public partial class AddChangeCodeSubscriptionType
    {
        
        private InvocationContextType invocationContextField;
        
        private string changeCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://serviceplatformen.dk/xml/schemas/InvocationContext/1/", Order=0)]
        public InvocationContextType InvocationContext
        {
            get
            {
                return this.invocationContextField;
            }
            set
            {
                this.invocationContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ChangeCode
        {
            get
            {
                return this.changeCodeField;
            }
            set
            {
                this.changeCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public partial class RemoveMunicipalityCodeSubscriptionResponseType
    {
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public partial class RemoveMunicipalityCodeSubscriptionType
    {
        
        private InvocationContextType invocationContextField;
        
        private string municipalityCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://serviceplatformen.dk/xml/schemas/InvocationContext/1/", Order=0)]
        public InvocationContextType InvocationContext
        {
            get
            {
                return this.invocationContextField;
            }
            set
            {
                this.invocationContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=1)]
        public string MunicipalityCode
        {
            get
            {
                return this.municipalityCodeField;
            }
            set
            {
                this.municipalityCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public partial class AddMunicipalityCodeSubscriptionResponseType
    {
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public partial class AddMunicipalityCodeSubscriptionType
    {
        
        private InvocationContextType invocationContextField;
        
        private string municipalityCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://serviceplatformen.dk/xml/schemas/InvocationContext/1/", Order=0)]
        public InvocationContextType InvocationContext
        {
            get
            {
                return this.invocationContextField;
            }
            set
            {
                this.invocationContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=1)]
        public string MunicipalityCode
        {
            get
            {
                return this.municipalityCodeField;
            }
            set
            {
                this.municipalityCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public partial class RemoveAgeRangeSubscriptionResponseType
    {
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public partial class RemoveAgeRangeSubscriptionType
    {
        
        private InvocationContextType invocationContextField;
        
        private AgeRange ageRangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://serviceplatformen.dk/xml/schemas/InvocationContext/1/", Order=0)]
        public InvocationContextType InvocationContext
        {
            get
            {
                return this.invocationContextField;
            }
            set
            {
                this.invocationContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AgeRange AgeRange
        {
            get
            {
                return this.ageRangeField;
            }
            set
            {
                this.ageRangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public partial class AddAgeRangeSubscriptionResponseType
    {
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public partial class AddAgeRangeSubscriptionType
    {
        
        private InvocationContextType invocationContextField;
        
        private AgeRange ageRangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://serviceplatformen.dk/xml/schemas/InvocationContext/1/", Order=0)]
        public InvocationContextType InvocationContext
        {
            get
            {
                return this.invocationContextField;
            }
            set
            {
                this.invocationContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AgeRange AgeRange
        {
            get
            {
                return this.ageRangeField;
            }
            set
            {
                this.ageRangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public partial class RemovePNRSubscriptionResponseType
    {
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public partial class RemovePNRSubscriptionType
    {
        
        private InvocationContextType invocationContextField;
        
        private string pNRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://serviceplatformen.dk/xml/schemas/InvocationContext/1/", Order=0)]
        public InvocationContextType InvocationContext
        {
            get
            {
                return this.invocationContextField;
            }
            set
            {
                this.invocationContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://serviceplatformen.dk/xml/schemas/cpr/PNR/1/", Order=1)]
        public string PNR
        {
            get
            {
                return this.pNRField;
            }
            set
            {
                this.pNRField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/")]
    public partial class AddPNRSubscriptionResponseType
    {
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPNRSubscriptionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/", Order=0)]
        public CprSubscriptionService.AddPNRSubscriptionType AddPNRSubscription;
        
        public AddPNRSubscriptionRequest()
        {
        }
        
        public AddPNRSubscriptionRequest(CprSubscriptionService.AddPNRSubscriptionType AddPNRSubscription)
        {
            this.AddPNRSubscription = AddPNRSubscription;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPNRSubscriptionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPNRSubscriptionResponse", Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/", Order=0)]
        public CprSubscriptionService.AddPNRSubscriptionResponseType AddPNRSubscriptionResponse1;
        
        public AddPNRSubscriptionResponse()
        {
        }
        
        public AddPNRSubscriptionResponse(CprSubscriptionService.AddPNRSubscriptionResponseType AddPNRSubscriptionResponse1)
        {
            this.AddPNRSubscriptionResponse1 = AddPNRSubscriptionResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemovePNRSubscriptionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/", Order=0)]
        public CprSubscriptionService.RemovePNRSubscriptionType RemovePNRSubscription;
        
        public RemovePNRSubscriptionRequest()
        {
        }
        
        public RemovePNRSubscriptionRequest(CprSubscriptionService.RemovePNRSubscriptionType RemovePNRSubscription)
        {
            this.RemovePNRSubscription = RemovePNRSubscription;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemovePNRSubscriptionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemovePNRSubscriptionResponse", Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/", Order=0)]
        public CprSubscriptionService.RemovePNRSubscriptionResponseType RemovePNRSubscriptionResponse1;
        
        public RemovePNRSubscriptionResponse()
        {
        }
        
        public RemovePNRSubscriptionResponse(CprSubscriptionService.RemovePNRSubscriptionResponseType RemovePNRSubscriptionResponse1)
        {
            this.RemovePNRSubscriptionResponse1 = RemovePNRSubscriptionResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAgeRangeSubscriptionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/", Order=0)]
        public CprSubscriptionService.AddAgeRangeSubscriptionType AddAgeRangeSubscription;
        
        public AddAgeRangeSubscriptionRequest()
        {
        }
        
        public AddAgeRangeSubscriptionRequest(CprSubscriptionService.AddAgeRangeSubscriptionType AddAgeRangeSubscription)
        {
            this.AddAgeRangeSubscription = AddAgeRangeSubscription;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAgeRangeSubscriptionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAgeRangeSubscriptionResponse", Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/", Order=0)]
        public CprSubscriptionService.AddAgeRangeSubscriptionResponseType AddAgeRangeSubscriptionResponse1;
        
        public AddAgeRangeSubscriptionResponse()
        {
        }
        
        public AddAgeRangeSubscriptionResponse(CprSubscriptionService.AddAgeRangeSubscriptionResponseType AddAgeRangeSubscriptionResponse1)
        {
            this.AddAgeRangeSubscriptionResponse1 = AddAgeRangeSubscriptionResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveAgeRangeSubscriptionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/", Order=0)]
        public CprSubscriptionService.RemoveAgeRangeSubscriptionType RemoveAgeRangeSubscription;
        
        public RemoveAgeRangeSubscriptionRequest()
        {
        }
        
        public RemoveAgeRangeSubscriptionRequest(CprSubscriptionService.RemoveAgeRangeSubscriptionType RemoveAgeRangeSubscription)
        {
            this.RemoveAgeRangeSubscription = RemoveAgeRangeSubscription;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveAgeRangeSubscriptionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveAgeRangeSubscriptionResponse", Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/", Order=0)]
        public CprSubscriptionService.RemoveAgeRangeSubscriptionResponseType RemoveAgeRangeSubscriptionResponse1;
        
        public RemoveAgeRangeSubscriptionResponse()
        {
        }
        
        public RemoveAgeRangeSubscriptionResponse(CprSubscriptionService.RemoveAgeRangeSubscriptionResponseType RemoveAgeRangeSubscriptionResponse1)
        {
            this.RemoveAgeRangeSubscriptionResponse1 = RemoveAgeRangeSubscriptionResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMunicipalityCodeSubscriptionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/", Order=0)]
        public CprSubscriptionService.AddMunicipalityCodeSubscriptionType AddMunicipalityCodeSubscription;
        
        public AddMunicipalityCodeSubscriptionRequest()
        {
        }
        
        public AddMunicipalityCodeSubscriptionRequest(CprSubscriptionService.AddMunicipalityCodeSubscriptionType AddMunicipalityCodeSubscription)
        {
            this.AddMunicipalityCodeSubscription = AddMunicipalityCodeSubscription;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMunicipalityCodeSubscriptionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMunicipalityCodeSubscriptionResponse", Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/", Order=0)]
        public CprSubscriptionService.AddMunicipalityCodeSubscriptionResponseType AddMunicipalityCodeSubscriptionResponse1;
        
        public AddMunicipalityCodeSubscriptionResponse()
        {
        }
        
        public AddMunicipalityCodeSubscriptionResponse(CprSubscriptionService.AddMunicipalityCodeSubscriptionResponseType AddMunicipalityCodeSubscriptionResponse1)
        {
            this.AddMunicipalityCodeSubscriptionResponse1 = AddMunicipalityCodeSubscriptionResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveMunicipalityCodeSubscriptionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/", Order=0)]
        public CprSubscriptionService.RemoveMunicipalityCodeSubscriptionType RemoveMunicipalityCodeSubscription;
        
        public RemoveMunicipalityCodeSubscriptionRequest()
        {
        }
        
        public RemoveMunicipalityCodeSubscriptionRequest(CprSubscriptionService.RemoveMunicipalityCodeSubscriptionType RemoveMunicipalityCodeSubscription)
        {
            this.RemoveMunicipalityCodeSubscription = RemoveMunicipalityCodeSubscription;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveMunicipalityCodeSubscriptionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveMunicipalityCodeSubscriptionResponse", Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/", Order=0)]
        public CprSubscriptionService.RemoveMunicipalityCodeSubscriptionResponseType RemoveMunicipalityCodeSubscriptionResponse1;
        
        public RemoveMunicipalityCodeSubscriptionResponse()
        {
        }
        
        public RemoveMunicipalityCodeSubscriptionResponse(CprSubscriptionService.RemoveMunicipalityCodeSubscriptionResponseType RemoveMunicipalityCodeSubscriptionResponse1)
        {
            this.RemoveMunicipalityCodeSubscriptionResponse1 = RemoveMunicipalityCodeSubscriptionResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddChangeCodeSubscriptionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/", Order=0)]
        public CprSubscriptionService.AddChangeCodeSubscriptionType AddChangeCodeSubscription;
        
        public AddChangeCodeSubscriptionRequest()
        {
        }
        
        public AddChangeCodeSubscriptionRequest(CprSubscriptionService.AddChangeCodeSubscriptionType AddChangeCodeSubscription)
        {
            this.AddChangeCodeSubscription = AddChangeCodeSubscription;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddChangeCodeSubscriptionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddChangeCodeSubscriptionResponse", Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/", Order=0)]
        public CprSubscriptionService.AddChangeCodeSubscriptionResponseType AddChangeCodeSubscriptionResponse1;
        
        public AddChangeCodeSubscriptionResponse()
        {
        }
        
        public AddChangeCodeSubscriptionResponse(CprSubscriptionService.AddChangeCodeSubscriptionResponseType AddChangeCodeSubscriptionResponse1)
        {
            this.AddChangeCodeSubscriptionResponse1 = AddChangeCodeSubscriptionResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveChangeCodeSubscriptionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/", Order=0)]
        public CprSubscriptionService.RemoveChangeCodeSubscriptionType RemoveChangeCodeSubscription;
        
        public RemoveChangeCodeSubscriptionRequest()
        {
        }
        
        public RemoveChangeCodeSubscriptionRequest(CprSubscriptionService.RemoveChangeCodeSubscriptionType RemoveChangeCodeSubscription)
        {
            this.RemoveChangeCodeSubscription = RemoveChangeCodeSubscription;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveChangeCodeSubscriptionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveChangeCodeSubscriptionResponse", Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/", Order=0)]
        public CprSubscriptionService.RemoveChangeCodeSubscriptionResponseType RemoveChangeCodeSubscriptionResponse1;
        
        public RemoveChangeCodeSubscriptionResponse()
        {
        }
        
        public RemoveChangeCodeSubscriptionResponse(CprSubscriptionService.RemoveChangeCodeSubscriptionResponseType RemoveChangeCodeSubscriptionResponse1)
        {
            this.RemoveChangeCodeSubscriptionResponse1 = RemoveChangeCodeSubscriptionResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNoFilterSubscriptionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/", Order=0)]
        public CprSubscriptionService.AddNoFilterSubscriptionType AddNoFilterSubscription;
        
        public AddNoFilterSubscriptionRequest()
        {
        }
        
        public AddNoFilterSubscriptionRequest(CprSubscriptionService.AddNoFilterSubscriptionType AddNoFilterSubscription)
        {
            this.AddNoFilterSubscription = AddNoFilterSubscription;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNoFilterSubscriptionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNoFilterSubscriptionResponse", Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/", Order=0)]
        public CprSubscriptionService.AddNoFilterSubscriptionResponseType AddNoFilterSubscriptionResponse1;
        
        public AddNoFilterSubscriptionResponse()
        {
        }
        
        public AddNoFilterSubscriptionResponse(CprSubscriptionService.AddNoFilterSubscriptionResponseType AddNoFilterSubscriptionResponse1)
        {
            this.AddNoFilterSubscriptionResponse1 = AddNoFilterSubscriptionResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveNoFilterSubscriptionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/", Order=0)]
        public CprSubscriptionService.RemoveNoFilterSubscriptionType RemoveNoFilterSubscription;
        
        public RemoveNoFilterSubscriptionRequest()
        {
        }
        
        public RemoveNoFilterSubscriptionRequest(CprSubscriptionService.RemoveNoFilterSubscriptionType RemoveNoFilterSubscription)
        {
            this.RemoveNoFilterSubscription = RemoveNoFilterSubscription;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveNoFilterSubscriptionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveNoFilterSubscriptionResponse", Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/", Order=0)]
        public CprSubscriptionService.RemoveNoFilterSubscriptionResponseType RemoveNoFilterSubscriptionResponse1;
        
        public RemoveNoFilterSubscriptionResponse()
        {
        }
        
        public RemoveNoFilterSubscriptionResponse(CprSubscriptionService.RemoveNoFilterSubscriptionResponseType RemoveNoFilterSubscriptionResponse1)
        {
            this.RemoveNoFilterSubscriptionResponse1 = RemoveNoFilterSubscriptionResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveAllRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/", Order=0)]
        public CprSubscriptionService.RemoveAllType RemoveAll;
        
        public RemoveAllRequest()
        {
        }
        
        public RemoveAllRequest(CprSubscriptionService.RemoveAllType RemoveAll)
        {
            this.RemoveAll = RemoveAll;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveAllResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveAllResponse", Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/", Order=0)]
        public CprSubscriptionService.RemoveAllResponseType RemoveAllResponse1;
        
        public RemoveAllResponse()
        {
        }
        
        public RemoveAllResponse(CprSubscriptionService.RemoveAllResponseType RemoveAllResponse1)
        {
            this.RemoveAllResponse1 = RemoveAllResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllFiltersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/", Order=0)]
        public CprSubscriptionService.GetAllFiltersType GetAllFilters;
        
        public GetAllFiltersRequest()
        {
        }
        
        public GetAllFiltersRequest(CprSubscriptionService.GetAllFiltersType GetAllFilters)
        {
            this.GetAllFilters = GetAllFilters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllFiltersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllFiltersResponse", Namespace="http://serviceplatformen.dk/xml/wsdl/soap11/CprSubscriptionService/1/", Order=0)]
        public CprSubscriptionService.GetAllFiltersResponseType GetAllFiltersResponse1;
        
        public GetAllFiltersResponse()
        {
        }
        
        public GetAllFiltersResponse(CprSubscriptionService.GetAllFiltersResponseType GetAllFiltersResponse1)
        {
            this.GetAllFiltersResponse1 = GetAllFiltersResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface CprSubscriptionWebServicePortTypeChannel : CprSubscriptionService.CprSubscriptionWebServicePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class CprSubscriptionWebServicePortTypeClient : System.ServiceModel.ClientBase<CprSubscriptionService.CprSubscriptionWebServicePortType>, CprSubscriptionService.CprSubscriptionWebServicePortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CprSubscriptionWebServicePortTypeClient() : 
                base(CprSubscriptionWebServicePortTypeClient.GetDefaultBinding(), CprSubscriptionWebServicePortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CprSubscriptionWebServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CprSubscriptionWebServicePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(CprSubscriptionWebServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), CprSubscriptionWebServicePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CprSubscriptionWebServicePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CprSubscriptionWebServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CprSubscriptionWebServicePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CprSubscriptionWebServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CprSubscriptionWebServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CprSubscriptionService.AddPNRSubscriptionResponse> CprSubscriptionService.CprSubscriptionWebServicePortType.AddPNRSubscriptionAsync(CprSubscriptionService.AddPNRSubscriptionRequest request)
        {
            return base.Channel.AddPNRSubscriptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CprSubscriptionService.AddPNRSubscriptionResponse> AddPNRSubscriptionAsync(CprSubscriptionService.AddPNRSubscriptionType AddPNRSubscription)
        {
            CprSubscriptionService.AddPNRSubscriptionRequest inValue = new CprSubscriptionService.AddPNRSubscriptionRequest();
            inValue.AddPNRSubscription = AddPNRSubscription;
            return ((CprSubscriptionService.CprSubscriptionWebServicePortType)(this)).AddPNRSubscriptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CprSubscriptionService.RemovePNRSubscriptionResponse> CprSubscriptionService.CprSubscriptionWebServicePortType.RemovePNRSubscriptionAsync(CprSubscriptionService.RemovePNRSubscriptionRequest request)
        {
            return base.Channel.RemovePNRSubscriptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CprSubscriptionService.RemovePNRSubscriptionResponse> RemovePNRSubscriptionAsync(CprSubscriptionService.RemovePNRSubscriptionType RemovePNRSubscription)
        {
            CprSubscriptionService.RemovePNRSubscriptionRequest inValue = new CprSubscriptionService.RemovePNRSubscriptionRequest();
            inValue.RemovePNRSubscription = RemovePNRSubscription;
            return ((CprSubscriptionService.CprSubscriptionWebServicePortType)(this)).RemovePNRSubscriptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CprSubscriptionService.AddAgeRangeSubscriptionResponse> CprSubscriptionService.CprSubscriptionWebServicePortType.AddAgeRangeSubscriptionAsync(CprSubscriptionService.AddAgeRangeSubscriptionRequest request)
        {
            return base.Channel.AddAgeRangeSubscriptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CprSubscriptionService.AddAgeRangeSubscriptionResponse> AddAgeRangeSubscriptionAsync(CprSubscriptionService.AddAgeRangeSubscriptionType AddAgeRangeSubscription)
        {
            CprSubscriptionService.AddAgeRangeSubscriptionRequest inValue = new CprSubscriptionService.AddAgeRangeSubscriptionRequest();
            inValue.AddAgeRangeSubscription = AddAgeRangeSubscription;
            return ((CprSubscriptionService.CprSubscriptionWebServicePortType)(this)).AddAgeRangeSubscriptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CprSubscriptionService.RemoveAgeRangeSubscriptionResponse> CprSubscriptionService.CprSubscriptionWebServicePortType.RemoveAgeRangeSubscriptionAsync(CprSubscriptionService.RemoveAgeRangeSubscriptionRequest request)
        {
            return base.Channel.RemoveAgeRangeSubscriptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CprSubscriptionService.RemoveAgeRangeSubscriptionResponse> RemoveAgeRangeSubscriptionAsync(CprSubscriptionService.RemoveAgeRangeSubscriptionType RemoveAgeRangeSubscription)
        {
            CprSubscriptionService.RemoveAgeRangeSubscriptionRequest inValue = new CprSubscriptionService.RemoveAgeRangeSubscriptionRequest();
            inValue.RemoveAgeRangeSubscription = RemoveAgeRangeSubscription;
            return ((CprSubscriptionService.CprSubscriptionWebServicePortType)(this)).RemoveAgeRangeSubscriptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CprSubscriptionService.AddMunicipalityCodeSubscriptionResponse> CprSubscriptionService.CprSubscriptionWebServicePortType.AddMunicipalityCodeSubscriptionAsync(CprSubscriptionService.AddMunicipalityCodeSubscriptionRequest request)
        {
            return base.Channel.AddMunicipalityCodeSubscriptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CprSubscriptionService.AddMunicipalityCodeSubscriptionResponse> AddMunicipalityCodeSubscriptionAsync(CprSubscriptionService.AddMunicipalityCodeSubscriptionType AddMunicipalityCodeSubscription)
        {
            CprSubscriptionService.AddMunicipalityCodeSubscriptionRequest inValue = new CprSubscriptionService.AddMunicipalityCodeSubscriptionRequest();
            inValue.AddMunicipalityCodeSubscription = AddMunicipalityCodeSubscription;
            return ((CprSubscriptionService.CprSubscriptionWebServicePortType)(this)).AddMunicipalityCodeSubscriptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CprSubscriptionService.RemoveMunicipalityCodeSubscriptionResponse> CprSubscriptionService.CprSubscriptionWebServicePortType.RemoveMunicipalityCodeSubscriptionAsync(CprSubscriptionService.RemoveMunicipalityCodeSubscriptionRequest request)
        {
            return base.Channel.RemoveMunicipalityCodeSubscriptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CprSubscriptionService.RemoveMunicipalityCodeSubscriptionResponse> RemoveMunicipalityCodeSubscriptionAsync(CprSubscriptionService.RemoveMunicipalityCodeSubscriptionType RemoveMunicipalityCodeSubscription)
        {
            CprSubscriptionService.RemoveMunicipalityCodeSubscriptionRequest inValue = new CprSubscriptionService.RemoveMunicipalityCodeSubscriptionRequest();
            inValue.RemoveMunicipalityCodeSubscription = RemoveMunicipalityCodeSubscription;
            return ((CprSubscriptionService.CprSubscriptionWebServicePortType)(this)).RemoveMunicipalityCodeSubscriptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CprSubscriptionService.AddChangeCodeSubscriptionResponse> CprSubscriptionService.CprSubscriptionWebServicePortType.AddChangeCodeSubscriptionAsync(CprSubscriptionService.AddChangeCodeSubscriptionRequest request)
        {
            return base.Channel.AddChangeCodeSubscriptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CprSubscriptionService.AddChangeCodeSubscriptionResponse> AddChangeCodeSubscriptionAsync(CprSubscriptionService.AddChangeCodeSubscriptionType AddChangeCodeSubscription)
        {
            CprSubscriptionService.AddChangeCodeSubscriptionRequest inValue = new CprSubscriptionService.AddChangeCodeSubscriptionRequest();
            inValue.AddChangeCodeSubscription = AddChangeCodeSubscription;
            return ((CprSubscriptionService.CprSubscriptionWebServicePortType)(this)).AddChangeCodeSubscriptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CprSubscriptionService.RemoveChangeCodeSubscriptionResponse> CprSubscriptionService.CprSubscriptionWebServicePortType.RemoveChangeCodeSubscriptionAsync(CprSubscriptionService.RemoveChangeCodeSubscriptionRequest request)
        {
            return base.Channel.RemoveChangeCodeSubscriptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CprSubscriptionService.RemoveChangeCodeSubscriptionResponse> RemoveChangeCodeSubscriptionAsync(CprSubscriptionService.RemoveChangeCodeSubscriptionType RemoveChangeCodeSubscription)
        {
            CprSubscriptionService.RemoveChangeCodeSubscriptionRequest inValue = new CprSubscriptionService.RemoveChangeCodeSubscriptionRequest();
            inValue.RemoveChangeCodeSubscription = RemoveChangeCodeSubscription;
            return ((CprSubscriptionService.CprSubscriptionWebServicePortType)(this)).RemoveChangeCodeSubscriptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CprSubscriptionService.AddNoFilterSubscriptionResponse> CprSubscriptionService.CprSubscriptionWebServicePortType.AddNoFilterSubscriptionAsync(CprSubscriptionService.AddNoFilterSubscriptionRequest request)
        {
            return base.Channel.AddNoFilterSubscriptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CprSubscriptionService.AddNoFilterSubscriptionResponse> AddNoFilterSubscriptionAsync(CprSubscriptionService.AddNoFilterSubscriptionType AddNoFilterSubscription)
        {
            CprSubscriptionService.AddNoFilterSubscriptionRequest inValue = new CprSubscriptionService.AddNoFilterSubscriptionRequest();
            inValue.AddNoFilterSubscription = AddNoFilterSubscription;
            return ((CprSubscriptionService.CprSubscriptionWebServicePortType)(this)).AddNoFilterSubscriptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CprSubscriptionService.RemoveNoFilterSubscriptionResponse> CprSubscriptionService.CprSubscriptionWebServicePortType.RemoveNoFilterSubscriptionAsync(CprSubscriptionService.RemoveNoFilterSubscriptionRequest request)
        {
            return base.Channel.RemoveNoFilterSubscriptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CprSubscriptionService.RemoveNoFilterSubscriptionResponse> RemoveNoFilterSubscriptionAsync(CprSubscriptionService.RemoveNoFilterSubscriptionType RemoveNoFilterSubscription)
        {
            CprSubscriptionService.RemoveNoFilterSubscriptionRequest inValue = new CprSubscriptionService.RemoveNoFilterSubscriptionRequest();
            inValue.RemoveNoFilterSubscription = RemoveNoFilterSubscription;
            return ((CprSubscriptionService.CprSubscriptionWebServicePortType)(this)).RemoveNoFilterSubscriptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CprSubscriptionService.RemoveAllResponse> CprSubscriptionService.CprSubscriptionWebServicePortType.RemoveAllAsync(CprSubscriptionService.RemoveAllRequest request)
        {
            return base.Channel.RemoveAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<CprSubscriptionService.RemoveAllResponse> RemoveAllAsync(CprSubscriptionService.RemoveAllType RemoveAll)
        {
            CprSubscriptionService.RemoveAllRequest inValue = new CprSubscriptionService.RemoveAllRequest();
            inValue.RemoveAll = RemoveAll;
            return ((CprSubscriptionService.CprSubscriptionWebServicePortType)(this)).RemoveAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CprSubscriptionService.GetAllFiltersResponse> CprSubscriptionService.CprSubscriptionWebServicePortType.GetAllFiltersAsync(CprSubscriptionService.GetAllFiltersRequest request)
        {
            return base.Channel.GetAllFiltersAsync(request);
        }
        
        public System.Threading.Tasks.Task<CprSubscriptionService.GetAllFiltersResponse> GetAllFiltersAsync(CprSubscriptionService.GetAllFiltersType GetAllFilters)
        {
            CprSubscriptionService.GetAllFiltersRequest inValue = new CprSubscriptionService.GetAllFiltersRequest();
            inValue.GetAllFilters = GetAllFilters;
            return ((CprSubscriptionService.CprSubscriptionWebServicePortType)(this)).GetAllFiltersAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CprSubscriptionWebServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CprSubscriptionWebServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/service/CPRSubscription/CPRSubscription/1/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CprSubscriptionWebServicePortTypeClient.GetBindingForEndpoint(EndpointConfiguration.CprSubscriptionWebServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CprSubscriptionWebServicePortTypeClient.GetEndpointAddress(EndpointConfiguration.CprSubscriptionWebServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            CprSubscriptionWebServicePort,
        }
    }
}
