//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetEmploymentChangedAtDate
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.sd.dk/sdws/GetEmploymentChangedAtDate20111201", ConfigurationName="GetEmploymentChangedAtDate.GetEmploymentChangedAtDate20111201PortType")]
    public interface GetEmploymentChangedAtDate20111201PortType
    {
        
        // CODEGEN: Generating message contract since the operation GetEmploymentChangedAtDate20111201Operation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="https://service.sd.dk/sdws/services/GetEmploymentChangedAtDate20111201", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SalaryAgreementType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SalaryCodeGroupType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EmploymentStatusType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProfessionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EmploymentDepartmentType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WorkingTimeType))]
        GetEmploymentChangedAtDate.GetEmploymentChangedAtDate20111201OperationResponse GetEmploymentChangedAtDate20111201Operation(GetEmploymentChangedAtDate.GetEmploymentChangedAtDate20111201OperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.sd.dk/sdws/services/GetEmploymentChangedAtDate20111201", ReplyAction="*")]
        System.Threading.Tasks.Task<GetEmploymentChangedAtDate.GetEmploymentChangedAtDate20111201OperationResponse> GetEmploymentChangedAtDate20111201OperationAsync(GetEmploymentChangedAtDate.GetEmploymentChangedAtDate20111201OperationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class GetEmploymentChangedAtDateRequestType
    {
        
        private string institutionIdentifierField;
        
        private string personCivilRegistrationIdentifierField;
        
        private string employmentIdentifierField;
        
        private string departmentIdentifierField;
        
        private string departmentLevelIdentifierField;
        
        private System.DateTime activationDateField;
        
        private System.DateTime activationTimeField;
        
        private bool activationTimeFieldSpecified;
        
        private System.DateTime deactivationDateField;
        
        private System.DateTime deactivationTimeField;
        
        private bool deactivationTimeFieldSpecified;
        
        private bool departmentIndicatorField;
        
        private bool employmentStatusIndicatorField;
        
        private bool professionIndicatorField;
        
        private bool salaryAgreementIndicatorField;
        
        private bool salaryCodeGroupIndicatorField;
        
        private bool workingTimeIndicatorField;
        
        private bool uUIDIndicatorField;
        
        private bool futureInformationIndicatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string InstitutionIdentifier
        {
            get
            {
                return this.institutionIdentifierField;
            }
            set
            {
                this.institutionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/", Order=1)]
        public string PersonCivilRegistrationIdentifier
        {
            get
            {
                return this.personCivilRegistrationIdentifierField;
            }
            set
            {
                this.personCivilRegistrationIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EmploymentIdentifier
        {
            get
            {
                return this.employmentIdentifierField;
            }
            set
            {
                this.employmentIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DepartmentIdentifier
        {
            get
            {
                return this.departmentIdentifierField;
            }
            set
            {
                this.departmentIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20080201/", Order=4)]
        public string DepartmentLevelIdentifier
        {
            get
            {
                return this.departmentLevelIdentifierField;
            }
            set
            {
                this.departmentLevelIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", DataType="date", Order=5)]
        public System.DateTime ActivationDate
        {
            get
            {
                return this.activationDateField;
            }
            set
            {
                this.activationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", DataType="time", Order=6)]
        public System.DateTime ActivationTime
        {
            get
            {
                return this.activationTimeField;
            }
            set
            {
                this.activationTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActivationTimeSpecified
        {
            get
            {
                return this.activationTimeFieldSpecified;
            }
            set
            {
                this.activationTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", DataType="date", Order=7)]
        public System.DateTime DeactivationDate
        {
            get
            {
                return this.deactivationDateField;
            }
            set
            {
                this.deactivationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", DataType="time", Order=8)]
        public System.DateTime DeactivationTime
        {
            get
            {
                return this.deactivationTimeField;
            }
            set
            {
                this.deactivationTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeactivationTimeSpecified
        {
            get
            {
                return this.deactivationTimeFieldSpecified;
            }
            set
            {
                this.deactivationTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070401/", Order=9)]
        public bool DepartmentIndicator
        {
            get
            {
                return this.departmentIndicatorField;
            }
            set
            {
                this.departmentIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070401/", Order=10)]
        public bool EmploymentStatusIndicator
        {
            get
            {
                return this.employmentStatusIndicatorField;
            }
            set
            {
                this.employmentStatusIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070401/", Order=11)]
        public bool ProfessionIndicator
        {
            get
            {
                return this.professionIndicatorField;
            }
            set
            {
                this.professionIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070401/", Order=12)]
        public bool SalaryAgreementIndicator
        {
            get
            {
                return this.salaryAgreementIndicatorField;
            }
            set
            {
                this.salaryAgreementIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070401/", Order=13)]
        public bool SalaryCodeGroupIndicator
        {
            get
            {
                return this.salaryCodeGroupIndicatorField;
            }
            set
            {
                this.salaryCodeGroupIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070401/", Order=14)]
        public bool WorkingTimeIndicator
        {
            get
            {
                return this.workingTimeIndicatorField;
            }
            set
            {
                this.workingTimeIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool UUIDIndicator
        {
            get
            {
                return this.uUIDIndicatorField;
            }
            set
            {
                this.uUIDIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070401/", Order=16)]
        public bool FutureInformationIndicator
        {
            get
            {
                return this.futureInformationIndicatorField;
            }
            set
            {
                this.futureInformationIndicatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SalaryAgreementTypeChangedAtDate))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class SalaryAgreementType
    {
        
        private System.DateTime activationDateField;
        
        private System.DateTime deactivationDateField;
        
        private string salaryAgreementIdentifierField;
        
        private string salaryClassIdentifierField;
        
        private string salaryScaleIdentifierField;
        
        private bool prepaidIndicatorField;
        
        private System.DateTime seniorityDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", DataType="date", Order=0)]
        public System.DateTime ActivationDate
        {
            get
            {
                return this.activationDateField;
            }
            set
            {
                this.activationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", DataType="date", Order=1)]
        public System.DateTime DeactivationDate
        {
            get
            {
                return this.deactivationDateField;
            }
            set
            {
                this.deactivationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070401/", Order=2)]
        public string SalaryAgreementIdentifier
        {
            get
            {
                return this.salaryAgreementIdentifierField;
            }
            set
            {
                this.salaryAgreementIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070401/", DataType="integer", Order=3)]
        public string SalaryClassIdentifier
        {
            get
            {
                return this.salaryClassIdentifierField;
            }
            set
            {
                this.salaryClassIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070401/", DataType="integer", Order=4)]
        public string SalaryScaleIdentifier
        {
            get
            {
                return this.salaryScaleIdentifierField;
            }
            set
            {
                this.salaryScaleIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070401/", Order=5)]
        public bool PrepaidIndicator
        {
            get
            {
                return this.prepaidIndicatorField;
            }
            set
            {
                this.prepaidIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070401/", DataType="date", Order=6)]
        public System.DateTime SeniorityDate
        {
            get
            {
                return this.seniorityDateField;
            }
            set
            {
                this.seniorityDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class SalaryAgreementTypeChangedAtDate : SalaryAgreementType
    {
        
        private System.DateTime changedAtDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime changedAtDate
        {
            get
            {
                return this.changedAtDateField;
            }
            set
            {
                this.changedAtDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SalaryCodeGroupTypeChangedAtDate))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class SalaryCodeGroupType
    {
        
        private System.DateTime activationDateField;
        
        private System.DateTime deactivationDateField;
        
        private string pensionCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", DataType="date", Order=0)]
        public System.DateTime ActivationDate
        {
            get
            {
                return this.activationDateField;
            }
            set
            {
                this.activationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", DataType="date", Order=1)]
        public System.DateTime DeactivationDate
        {
            get
            {
                return this.deactivationDateField;
            }
            set
            {
                this.deactivationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PensionCode
        {
            get
            {
                return this.pensionCodeField;
            }
            set
            {
                this.pensionCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class SalaryCodeGroupTypeChangedAtDate : SalaryCodeGroupType
    {
        
        private System.DateTime changedAtDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime changedAtDate
        {
            get
            {
                return this.changedAtDateField;
            }
            set
            {
                this.changedAtDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EmploymentStatusTypeChangedAtDate))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class EmploymentStatusType
    {
        
        private System.DateTime activationDateField;
        
        private System.DateTime deactivationDateField;
        
        private string employmentStatusCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", DataType="date", Order=0)]
        public System.DateTime ActivationDate
        {
            get
            {
                return this.activationDateField;
            }
            set
            {
                this.activationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", DataType="date", Order=1)]
        public System.DateTime DeactivationDate
        {
            get
            {
                return this.deactivationDateField;
            }
            set
            {
                this.deactivationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EmploymentStatusCode
        {
            get
            {
                return this.employmentStatusCodeField;
            }
            set
            {
                this.employmentStatusCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class EmploymentStatusTypeChangedAtDate : EmploymentStatusType
    {
        
        private System.DateTime changedAtDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime changedAtDate
        {
            get
            {
                return this.changedAtDateField;
            }
            set
            {
                this.changedAtDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProfessionTypeChangedAtDate))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class ProfessionType
    {
        
        private System.DateTime activationDateField;
        
        private System.DateTime deactivationDateField;
        
        private string jobPositionIdentifierField;
        
        private string employmentNameField;
        
        private string appointmentCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", DataType="date", Order=0)]
        public System.DateTime ActivationDate
        {
            get
            {
                return this.activationDateField;
            }
            set
            {
                this.activationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", DataType="date", Order=1)]
        public System.DateTime DeactivationDate
        {
            get
            {
                return this.deactivationDateField;
            }
            set
            {
                this.deactivationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string JobPositionIdentifier
        {
            get
            {
                return this.jobPositionIdentifierField;
            }
            set
            {
                this.jobPositionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string EmploymentName
        {
            get
            {
                return this.employmentNameField;
            }
            set
            {
                this.employmentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070401/", Order=4)]
        public string AppointmentCode
        {
            get
            {
                return this.appointmentCodeField;
            }
            set
            {
                this.appointmentCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class ProfessionTypeChangedAtDate : ProfessionType
    {
        
        private System.DateTime changedAtDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime changedAtDate
        {
            get
            {
                return this.changedAtDateField;
            }
            set
            {
                this.changedAtDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DepartmentTypeChangedAtDate))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class EmploymentDepartmentType
    {
        
        private System.DateTime activationDateField;
        
        private System.DateTime deactivationDateField;
        
        private string departmentIdentifierField;
        
        private string departmentUUIDIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", DataType="date", Order=0)]
        public System.DateTime ActivationDate
        {
            get
            {
                return this.activationDateField;
            }
            set
            {
                this.activationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", DataType="date", Order=1)]
        public System.DateTime DeactivationDate
        {
            get
            {
                return this.deactivationDateField;
            }
            set
            {
                this.deactivationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DepartmentIdentifier
        {
            get
            {
                return this.departmentIdentifierField;
            }
            set
            {
                this.departmentIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DepartmentUUIDIdentifier
        {
            get
            {
                return this.departmentUUIDIdentifierField;
            }
            set
            {
                this.departmentUUIDIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class DepartmentTypeChangedAtDate : EmploymentDepartmentType
    {
        
        private System.DateTime changedAtDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime changedAtDate
        {
            get
            {
                return this.changedAtDateField;
            }
            set
            {
                this.changedAtDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070401/")]
    public partial class HourQuantityStructureType
    {
        
        private _periodCodeType periodCodeField;
        
        private bool periodCodeFieldSpecified;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public _periodCodeType periodCode
        {
            get
            {
                return this.periodCodeField;
            }
            set
            {
                this.periodCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodCodeSpecified
        {
            get
            {
                return this.periodCodeFieldSpecified;
            }
            set
            {
                this.periodCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070401/")]
    public enum _periodCodeType
    {
        
        /// <remarks/>
        day,
        
        /// <remarks/>
        week,
        
        /// <remarks/>
        fortnight,
        
        /// <remarks/>
        halfmonth,
        
        /// <remarks/>
        month,
        
        /// <remarks/>
        year,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WorkingTimeTypeChangedAtDate))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class WorkingTimeType
    {
        
        private System.DateTime activationDateField;
        
        private System.DateTime deactivationDateField;
        
        private decimal occupationRateField;
        
        private bool occupationRateFieldSpecified;
        
        private decimal salaryRateField;
        
        private bool salaryRateFieldSpecified;
        
        private HourQuantityStructureType occupationHourQuantityField;
        
        private HourQuantityStructureType salaryHourQuantityField;
        
        private bool salariedIndicatorField;
        
        private bool fullTimeIndicatorField;
        
        private bool fullTimeIndicatorFieldSpecified;
        
        private bool automaticRaiseIndicatorField;
        
        private bool automaticRaiseIndicatorFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", DataType="date", Order=0)]
        public System.DateTime ActivationDate
        {
            get
            {
                return this.activationDateField;
            }
            set
            {
                this.activationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", DataType="date", Order=1)]
        public System.DateTime DeactivationDate
        {
            get
            {
                return this.deactivationDateField;
            }
            set
            {
                this.deactivationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070401/", Order=2)]
        public decimal OccupationRate
        {
            get
            {
                return this.occupationRateField;
            }
            set
            {
                this.occupationRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OccupationRateSpecified
        {
            get
            {
                return this.occupationRateFieldSpecified;
            }
            set
            {
                this.occupationRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070401/", Order=3)]
        public decimal SalaryRate
        {
            get
            {
                return this.salaryRateField;
            }
            set
            {
                this.salaryRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalaryRateSpecified
        {
            get
            {
                return this.salaryRateFieldSpecified;
            }
            set
            {
                this.salaryRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public HourQuantityStructureType OccupationHourQuantity
        {
            get
            {
                return this.occupationHourQuantityField;
            }
            set
            {
                this.occupationHourQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public HourQuantityStructureType SalaryHourQuantity
        {
            get
            {
                return this.salaryHourQuantityField;
            }
            set
            {
                this.salaryHourQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070401/", Order=6)]
        public bool SalariedIndicator
        {
            get
            {
                return this.salariedIndicatorField;
            }
            set
            {
                this.salariedIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070401/", Order=7)]
        public bool FullTimeIndicator
        {
            get
            {
                return this.fullTimeIndicatorField;
            }
            set
            {
                this.fullTimeIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FullTimeIndicatorSpecified
        {
            get
            {
                return this.fullTimeIndicatorFieldSpecified;
            }
            set
            {
                this.fullTimeIndicatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070401/", Order=8)]
        public bool AutomaticRaiseIndicator
        {
            get
            {
                return this.automaticRaiseIndicatorField;
            }
            set
            {
                this.automaticRaiseIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AutomaticRaiseIndicatorSpecified
        {
            get
            {
                return this.automaticRaiseIndicatorFieldSpecified;
            }
            set
            {
                this.automaticRaiseIndicatorFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class WorkingTimeTypeChangedAtDate : WorkingTimeType
    {
        
        private System.DateTime changedAtDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime changedAtDate
        {
            get
            {
                return this.changedAtDateField;
            }
            set
            {
                this.changedAtDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class EmploymentTypeChangedAtDate
    {
        
        private string employmentIdentifierField;
        
        private System.DateTime employmentDateField;
        
        private bool employmentDateFieldSpecified;
        
        private System.DateTime anniversaryDateField;
        
        private bool anniversaryDateFieldSpecified;
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EmploymentIdentifier
        {
            get
            {
                return this.employmentIdentifierField;
            }
            set
            {
                this.employmentIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070401/", DataType="date", Order=1)]
        public System.DateTime EmploymentDate
        {
            get
            {
                return this.employmentDateField;
            }
            set
            {
                this.employmentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EmploymentDateSpecified
        {
            get
            {
                return this.employmentDateFieldSpecified;
            }
            set
            {
                this.employmentDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime AnniversaryDate
        {
            get
            {
                return this.anniversaryDateField;
            }
            set
            {
                this.anniversaryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnniversaryDateSpecified
        {
            get
            {
                return this.anniversaryDateFieldSpecified;
            }
            set
            {
                this.anniversaryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EmploymentDepartment", typeof(DepartmentTypeChangedAtDate), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("EmploymentStatus", typeof(EmploymentStatusTypeChangedAtDate), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("Profession", typeof(ProfessionTypeChangedAtDate), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("SalaryAgreement", typeof(SalaryAgreementTypeChangedAtDate), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("SalaryCodeGroup", typeof(SalaryCodeGroupTypeChangedAtDate), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("WorkingTime", typeof(WorkingTimeTypeChangedAtDate), Order=3)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class PersonTypeChangedAtDate
    {
        
        private string personCivilRegistrationIdentifierField;
        
        private EmploymentTypeChangedAtDate[] employmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/", Order=0)]
        public string PersonCivilRegistrationIdentifier
        {
            get
            {
                return this.personCivilRegistrationIdentifierField;
            }
            set
            {
                this.personCivilRegistrationIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Employment", Order=1)]
        public EmploymentTypeChangedAtDate[] Employment
        {
            get
            {
                return this.employmentField;
            }
            set
            {
                this.employmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class GetEmploymentChangedAtDateType
    {
        
        private GetEmploymentChangedAtDateRequestType requestStructureField;
        
        private PersonTypeChangedAtDate[] personField;
        
        private System.DateTime creationDateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public GetEmploymentChangedAtDateRequestType RequestStructure
        {
            get
            {
                return this.requestStructureField;
            }
            set
            {
                this.requestStructureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Person", Order=1)]
        public PersonTypeChangedAtDate[] Person
        {
            get
            {
                return this.personField;
            }
            set
            {
                this.personField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime creationDateTime
        {
            get
            {
                return this.creationDateTimeField;
            }
            set
            {
                this.creationDateTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmploymentChangedAtDate20111201OperationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01", Order=0)]
        public GetEmploymentChangedAtDate.GetEmploymentChangedAtDateRequestType GetEmploymentChangedAtDate;
        
        public GetEmploymentChangedAtDate20111201OperationRequest()
        {
        }
        
        public GetEmploymentChangedAtDate20111201OperationRequest(GetEmploymentChangedAtDate.GetEmploymentChangedAtDateRequestType GetEmploymentChangedAtDate)
        {
            this.GetEmploymentChangedAtDate = GetEmploymentChangedAtDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmploymentChangedAtDate20111201OperationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01", Order=0)]
        public GetEmploymentChangedAtDate.GetEmploymentChangedAtDateType GetEmploymentChangedAtDate20111201;
        
        public GetEmploymentChangedAtDate20111201OperationResponse()
        {
        }
        
        public GetEmploymentChangedAtDate20111201OperationResponse(GetEmploymentChangedAtDate.GetEmploymentChangedAtDateType GetEmploymentChangedAtDate20111201)
        {
            this.GetEmploymentChangedAtDate20111201 = GetEmploymentChangedAtDate20111201;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface GetEmploymentChangedAtDate20111201PortTypeChannel : GetEmploymentChangedAtDate.GetEmploymentChangedAtDate20111201PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class GetEmploymentChangedAtDate20111201PortTypeClient : System.ServiceModel.ClientBase<GetEmploymentChangedAtDate.GetEmploymentChangedAtDate20111201PortType>, GetEmploymentChangedAtDate.GetEmploymentChangedAtDate20111201PortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GetEmploymentChangedAtDate20111201PortTypeClient() : 
                base(GetEmploymentChangedAtDate20111201PortTypeClient.GetDefaultBinding(), GetEmploymentChangedAtDate20111201PortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.GetEmploymentChangedAtDate20111201.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetEmploymentChangedAtDate20111201PortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(GetEmploymentChangedAtDate20111201PortTypeClient.GetBindingForEndpoint(endpointConfiguration), GetEmploymentChangedAtDate20111201PortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetEmploymentChangedAtDate20111201PortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GetEmploymentChangedAtDate20111201PortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetEmploymentChangedAtDate20111201PortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GetEmploymentChangedAtDate20111201PortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetEmploymentChangedAtDate20111201PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetEmploymentChangedAtDate.GetEmploymentChangedAtDate20111201OperationResponse GetEmploymentChangedAtDate.GetEmploymentChangedAtDate20111201PortType.GetEmploymentChangedAtDate20111201Operation(GetEmploymentChangedAtDate.GetEmploymentChangedAtDate20111201OperationRequest request)
        {
            return base.Channel.GetEmploymentChangedAtDate20111201Operation(request);
        }
        
        public GetEmploymentChangedAtDate.GetEmploymentChangedAtDateType GetEmploymentChangedAtDate20111201Operation(GetEmploymentChangedAtDate.GetEmploymentChangedAtDateRequestType GetEmploymentChangedAtDate)
        {
            GetEmploymentChangedAtDate.GetEmploymentChangedAtDate20111201OperationRequest inValue = new GetEmploymentChangedAtDate.GetEmploymentChangedAtDate20111201OperationRequest();
            inValue.GetEmploymentChangedAtDate = GetEmploymentChangedAtDate;
            GetEmploymentChangedAtDate.GetEmploymentChangedAtDate20111201OperationResponse retVal = ((GetEmploymentChangedAtDate.GetEmploymentChangedAtDate20111201PortType)(this)).GetEmploymentChangedAtDate20111201Operation(inValue);
            return retVal.GetEmploymentChangedAtDate20111201;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetEmploymentChangedAtDate.GetEmploymentChangedAtDate20111201OperationResponse> GetEmploymentChangedAtDate.GetEmploymentChangedAtDate20111201PortType.GetEmploymentChangedAtDate20111201OperationAsync(GetEmploymentChangedAtDate.GetEmploymentChangedAtDate20111201OperationRequest request)
        {
            return base.Channel.GetEmploymentChangedAtDate20111201OperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetEmploymentChangedAtDate.GetEmploymentChangedAtDate20111201OperationResponse> GetEmploymentChangedAtDate20111201OperationAsync(GetEmploymentChangedAtDate.GetEmploymentChangedAtDateRequestType GetEmploymentChangedAtDate)
        {
            GetEmploymentChangedAtDate.GetEmploymentChangedAtDate20111201OperationRequest inValue = new GetEmploymentChangedAtDate.GetEmploymentChangedAtDate20111201OperationRequest();
            inValue.GetEmploymentChangedAtDate = GetEmploymentChangedAtDate;
            return ((GetEmploymentChangedAtDate.GetEmploymentChangedAtDate20111201PortType)(this)).GetEmploymentChangedAtDate20111201OperationAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GetEmploymentChangedAtDate20111201))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GetEmploymentChangedAtDate20111201))
            {
                return new System.ServiceModel.EndpointAddress("https://service.sd.dk/sdws/services/GetEmploymentChangedAtDate20111201");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GetEmploymentChangedAtDate20111201PortTypeClient.GetBindingForEndpoint(EndpointConfiguration.GetEmploymentChangedAtDate20111201);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GetEmploymentChangedAtDate20111201PortTypeClient.GetEndpointAddress(EndpointConfiguration.GetEmploymentChangedAtDate20111201);
        }
        
        public enum EndpointConfiguration
        {
            
            GetEmploymentChangedAtDate20111201,
        }
    }
}
