//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetInstitution
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.sd.dk/sdws/GetInstitution20111201", ConfigurationName="GetInstitution.GetInstitution20111201PortType")]
    public interface GetInstitution20111201PortType
    {
        
        // CODEGEN: Generating message contract since the operation GetInstitution20111201Operation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="https://service.sd.dk/sdws/services/GetInstitution20111201", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GetInstitution.GetInstitution20111201OperationResponse GetInstitution20111201Operation(GetInstitution.GetInstitution20111201OperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.sd.dk/sdws/services/GetInstitution20111201", ReplyAction="*")]
        System.Threading.Tasks.Task<GetInstitution.GetInstitution20111201OperationResponse> GetInstitution20111201OperationAsync(GetInstitution.GetInstitution20111201OperationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class GetInstitutionRequestType
    {
        
        private string regionIdentifierField;
        
        private string regionUUIDIdentifierField;
        
        private string institutionIdentifierField;
        
        private string institutionUUIDIdentifierField;
        
        private bool administrationIndicatorField;
        
        private bool contactInformationIndicatorField;
        
        private bool postalAddressIndicatorField;
        
        private bool productionUnitIndicatorField;
        
        private bool uUIDIndicatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RegionIdentifier
        {
            get
            {
                return this.regionIdentifierField;
            }
            set
            {
                this.regionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RegionUUIDIdentifier
        {
            get
            {
                return this.regionUUIDIdentifierField;
            }
            set
            {
                this.regionUUIDIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string InstitutionIdentifier
        {
            get
            {
                return this.institutionIdentifierField;
            }
            set
            {
                this.institutionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string InstitutionUUIDIdentifier
        {
            get
            {
                return this.institutionUUIDIdentifierField;
            }
            set
            {
                this.institutionUUIDIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20080201/", Order=4)]
        public bool AdministrationIndicator
        {
            get
            {
                return this.administrationIndicatorField;
            }
            set
            {
                this.administrationIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", Order=5)]
        public bool ContactInformationIndicator
        {
            get
            {
                return this.contactInformationIndicatorField;
            }
            set
            {
                this.contactInformationIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", Order=6)]
        public bool PostalAddressIndicator
        {
            get
            {
                return this.postalAddressIndicatorField;
            }
            set
            {
                this.postalAddressIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool ProductionUnitIndicator
        {
            get
            {
                return this.productionUnitIndicatorField;
            }
            set
            {
                this.productionUnitIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool UUIDIndicator
        {
            get
            {
                return this.uUIDIndicatorField;
            }
            set
            {
                this.uUIDIndicatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20080201/")]
    public partial class ContactInformationType
    {
        
        private string[] telephoneNumberIdentifierField;
        
        private string[] emailAddressIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TelephoneNumberIdentifier", Namespace="http://rep.oio.dk/itst.dk/xml/schemas/2005/01/10/", Order=0)]
        public string[] TelephoneNumberIdentifier
        {
            get
            {
                return this.telephoneNumberIdentifierField;
            }
            set
            {
                this.telephoneNumberIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EmailAddressIdentifier", Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2005/03/15/", Order=1)]
        public string[] EmailAddressIdentifier
        {
            get
            {
                return this.emailAddressIdentifierField;
            }
            set
            {
                this.emailAddressIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
    public partial class CountryIdentificationCodeType
    {
        
        private _CountryIdentificationSchemeType schemeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public _CountryIdentificationSchemeType scheme
        {
            get
            {
                return this.schemeField;
            }
            set
            {
                this.schemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
    public enum _CountryIdentificationSchemeType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("iso3166-alpha2")]
        iso3166alpha2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("iso3166-alpha3")]
        iso3166alpha3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("un-numeric3")]
        unnumeric3,
        
        /// <remarks/>
        imk,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/")]
    public partial class PostalAddressType
    {
        
        private string standardAddressIdentifierField;
        
        private string postalCodeField;
        
        private string districtNameField;
        
        private string municipalityCodeField;
        
        private CountryIdentificationCodeType countryIdentificationCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/itst.dk/xml/schemas/2005/06/24/", Order=0)]
        public string StandardAddressIdentifier
        {
            get
            {
                return this.standardAddressIdentifierField;
            }
            set
            {
                this.standardAddressIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/", Order=2)]
        public string DistrictName
        {
            get
            {
                return this.districtNameField;
            }
            set
            {
                this.districtNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/", Order=3)]
        public string MunicipalityCode
        {
            get
            {
                return this.municipalityCodeField;
            }
            set
            {
                this.municipalityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=4)]
        public CountryIdentificationCodeType CountryIdentificationCode
        {
            get
            {
                return this.countryIdentificationCodeField;
            }
            set
            {
                this.countryIdentificationCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class InstitutionType
    {
        
        private string institutionIdentifierField;
        
        private string institutionUUIDIdentifierField;
        
        private string institutionNameField;
        
        private string administrationInstitutionIdentifierField;
        
        private string administrationInstitutionUUIDIdentifierField;
        
        private string serviceInstitutionIdentifierField;
        
        private string serviceInstitutionUUIDIdentifierField;
        
        private string productionUnitIdentifierField;
        
        private PostalAddressType postalAddressField;
        
        private ContactInformationType contactInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string InstitutionIdentifier
        {
            get
            {
                return this.institutionIdentifierField;
            }
            set
            {
                this.institutionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InstitutionUUIDIdentifier
        {
            get
            {
                return this.institutionUUIDIdentifierField;
            }
            set
            {
                this.institutionUUIDIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20080201/", Order=2)]
        public string InstitutionName
        {
            get
            {
                return this.institutionNameField;
            }
            set
            {
                this.institutionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AdministrationInstitutionIdentifier
        {
            get
            {
                return this.administrationInstitutionIdentifierField;
            }
            set
            {
                this.administrationInstitutionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AdministrationInstitutionUUIDIdentifier
        {
            get
            {
                return this.administrationInstitutionUUIDIdentifierField;
            }
            set
            {
                this.administrationInstitutionUUIDIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ServiceInstitutionIdentifier
        {
            get
            {
                return this.serviceInstitutionIdentifierField;
            }
            set
            {
                this.serviceInstitutionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ServiceInstitutionUUIDIdentifier
        {
            get
            {
                return this.serviceInstitutionUUIDIdentifierField;
            }
            set
            {
                this.serviceInstitutionUUIDIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cvr.dk/xml/schemas/2005/03/22/", Order=7)]
        public string ProductionUnitIdentifier
        {
            get
            {
                return this.productionUnitIdentifierField;
            }
            set
            {
                this.productionUnitIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20070301/", Order=8)]
        public PostalAddressType PostalAddress
        {
            get
            {
                return this.postalAddressField;
            }
            set
            {
                this.postalAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20080201/", Order=9)]
        public ContactInformationType ContactInformation
        {
            get
            {
                return this.contactInformationField;
            }
            set
            {
                this.contactInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class RegionType
    {
        
        private string regionIdentifierField;
        
        private string regionUUIDIdentifierField;
        
        private string regionNameField;
        
        private InstitutionType[] institutionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RegionIdentifier
        {
            get
            {
                return this.regionIdentifierField;
            }
            set
            {
                this.regionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RegionUUIDIdentifier
        {
            get
            {
                return this.regionUUIDIdentifierField;
            }
            set
            {
                this.regionUUIDIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/sd.dk/xml.schema/20080201/", Order=2)]
        public string RegionName
        {
            get
            {
                return this.regionNameField;
            }
            set
            {
                this.regionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Institution", Order=3)]
        public InstitutionType[] Institution
        {
            get
            {
                return this.institutionField;
            }
            set
            {
                this.institutionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01")]
    public partial class GetInstitution20111201Type
    {
        
        private GetInstitutionRequestType requestStructureField;
        
        private RegionType[] regionField;
        
        private System.DateTime creationDateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public GetInstitutionRequestType RequestStructure
        {
            get
            {
                return this.requestStructureField;
            }
            set
            {
                this.requestStructureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Region", Order=1)]
        public RegionType[] Region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime creationDateTime
        {
            get
            {
                return this.creationDateTimeField;
            }
            set
            {
                this.creationDateTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInstitution20111201OperationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01", Order=0)]
        public GetInstitution.GetInstitutionRequestType GetInstitution;
        
        public GetInstitution20111201OperationRequest()
        {
        }
        
        public GetInstitution20111201OperationRequest(GetInstitution.GetInstitutionRequestType GetInstitution)
        {
            this.GetInstitution = GetInstitution;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInstitution20111201OperationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:oio:sd:snitflader:2011.12.01", Order=0)]
        public GetInstitution.GetInstitution20111201Type GetInstitution20111201;
        
        public GetInstitution20111201OperationResponse()
        {
        }
        
        public GetInstitution20111201OperationResponse(GetInstitution.GetInstitution20111201Type GetInstitution20111201)
        {
            this.GetInstitution20111201 = GetInstitution20111201;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface GetInstitution20111201PortTypeChannel : GetInstitution.GetInstitution20111201PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class GetInstitution20111201PortTypeClient : System.ServiceModel.ClientBase<GetInstitution.GetInstitution20111201PortType>, GetInstitution.GetInstitution20111201PortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GetInstitution20111201PortTypeClient() : 
                base(GetInstitution20111201PortTypeClient.GetDefaultBinding(), GetInstitution20111201PortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.GetInstitution20111201.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetInstitution20111201PortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(GetInstitution20111201PortTypeClient.GetBindingForEndpoint(endpointConfiguration), GetInstitution20111201PortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetInstitution20111201PortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GetInstitution20111201PortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetInstitution20111201PortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GetInstitution20111201PortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetInstitution20111201PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetInstitution.GetInstitution20111201OperationResponse GetInstitution.GetInstitution20111201PortType.GetInstitution20111201Operation(GetInstitution.GetInstitution20111201OperationRequest request)
        {
            return base.Channel.GetInstitution20111201Operation(request);
        }
        
        public GetInstitution.GetInstitution20111201Type GetInstitution20111201Operation(GetInstitution.GetInstitutionRequestType GetInstitution)
        {
            GetInstitution.GetInstitution20111201OperationRequest inValue = new GetInstitution.GetInstitution20111201OperationRequest();
            inValue.GetInstitution = GetInstitution;
            GetInstitution.GetInstitution20111201OperationResponse retVal = ((GetInstitution.GetInstitution20111201PortType)(this)).GetInstitution20111201Operation(inValue);
            return retVal.GetInstitution20111201;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetInstitution.GetInstitution20111201OperationResponse> GetInstitution.GetInstitution20111201PortType.GetInstitution20111201OperationAsync(GetInstitution.GetInstitution20111201OperationRequest request)
        {
            return base.Channel.GetInstitution20111201OperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetInstitution.GetInstitution20111201OperationResponse> GetInstitution20111201OperationAsync(GetInstitution.GetInstitutionRequestType GetInstitution)
        {
            GetInstitution.GetInstitution20111201OperationRequest inValue = new GetInstitution.GetInstitution20111201OperationRequest();
            inValue.GetInstitution = GetInstitution;
            return ((GetInstitution.GetInstitution20111201PortType)(this)).GetInstitution20111201OperationAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GetInstitution20111201))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GetInstitution20111201))
            {
                return new System.ServiceModel.EndpointAddress("https://service.sd.dk/sdws/sdws/services/GetInstitution20111201");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GetInstitution20111201PortTypeClient.GetBindingForEndpoint(EndpointConfiguration.GetInstitution20111201);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GetInstitution20111201PortTypeClient.GetEndpointAddress(EndpointConfiguration.GetInstitution20111201);
        }
        
        public enum EndpointConfiguration
        {
            
            GetInstitution20111201,
        }
    }
}
